export const mockedTags = [
  {
    tagId: 1,
    tagType: 'organisation',
    name: 'Aarhus Universitet',
    tagLine: null,
    country: null,
    popularity: 87,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/100/200/300',
    pageLink: null,
  },
  {
    tagId: 2,
    tagType: 'organisation',
    name: 'AB.ACUS SRL',
    tagLine: null,
    country: null,
    popularity: 81,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/101/200/300',
    pageLink: null,
  },
  {
    tagId: 3,
    tagType: 'organisation',
    name: 'AIT',
    tagLine: 'Austrian Institute Of Technology GmbH',
    country: null,
    popularity: 64,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/102/200/300',
    pageLink: null,
  },
  {
    tagId: 4,
    tagType: 'organisation',
    name: 'ANCD',
    tagLine: 'Agenția Națională pentru Cercetare și Dezvoltare',
    country: null,
    popularity: 5,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/103/200/300',
    pageLink: null,
  },
  {
    tagId: 5,
    tagType: 'organisation',
    name: 'APRE',
    tagLine: null,
    country: null,
    popularity: 14,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/104/200/300',
    pageLink: null,
  },
  {
    tagId: 6,
    tagType: 'organisation',
    name: 'ARCTIK SRL',
    tagLine: null,
    country: null,
    popularity: 78,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/105/200/300',
    pageLink: null,
  },
  {
    tagId: 7,
    tagType: 'organisation',
    name: 'Aristotelio Panepistimio Thessalonikis',
    tagLine: null,
    country: 'Greece',
    popularity: 28,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/106/200/300',
    pageLink: null,
  },
  {
    tagId: 8,
    tagType: 'organisation',
    name: 'Association TRACES',
    tagLine: null,
    country: null,
    popularity: 19,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/107/200/300',
    pageLink: null,
  },
  {
    tagId: 9,
    tagType: 'organisation',
    name: 'Aston University',
    tagLine: null,
    country: null,
    popularity: 20,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/108/200/300',
    pageLink: null,
  },
  {
    tagId: 10,
    tagType: 'organisation',
    name: 'Business Hippie Club',
    tagLine: null,
    country: null,
    popularity: 29,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/109/200/300',
    pageLink: null,
  },
  {
    tagId: 11,
    tagType: 'organisation',
    name: 'Centro Internazionale di Altistudi Agronomici Mediterranei',
    tagLine: null,
    country: null,
    popularity: 26,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/110/200/300',
    pageLink: null,
  },
  {
    tagId: 12,
    tagType: 'organisation',
    name: 'CERS',
    tagLine: 'Kozgazdasag - Es Regionalis Tudomanyi Kutatokozpont',
    country: null,
    popularity: 9,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/111/200/300',
    pageLink: null,
  },
  {
    tagId: 13,
    tagType: 'organisation',
    name: 'Ceske Priority',
    tagLine:
      'non-governmental and non-profit think-tank of researchers and public sector experts',
    country: null,
    popularity: 58,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/112/200/300',
    pageLink: null,
  },
  {
    tagId: 14,
    tagType: 'organisation',
    name: 'CNR',
    tagLine: 'Consiglio Nazionale delle Ricerche',
    country: null,
    popularity: 29,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/113/200/300',
    pageLink: null,
  },
  {
    tagId: 15,
    tagType: 'organisation',
    name: 'CONSULAI',
    tagLine: 'Consultoria Agroindustrial LDA',
    country: null,
    popularity: 61,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/114/200/300',
    pageLink: null,
  },
  {
    tagId: 16,
    tagType: 'organisation',
    name: 'Copernicus Science Centre',
    tagLine: null,
    country: null,
    popularity: 59,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/115/200/300',
    pageLink: null,
  },
  {
    tagId: 17,
    tagType: 'organisation',
    name: 'Council of the European Union',
    tagLine: null,
    country: null,
    popularity: 34,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/116/200/300',
    pageLink: null,
  },
  {
    tagId: 18,
    tagType: 'organisation',
    name: 'CRN',
    tagLine: 'Comparative Research Network',
    country: null,
    popularity: 16,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/117/200/300',
    pageLink: null,
  },
  {
    tagId: 19,
    tagType: 'organisation',
    name: 'Development Centre of Võru County',
    tagLine: null,
    country: null,
    popularity: 60,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/118/200/300',
    pageLink: null,
  },
  {
    tagId: 20,
    tagType: 'organisation',
    name: 'DLR',
    tagLine: 'Deutsches Zentrum Fur Luft - Und Raumfahrt',
    country: null,
    popularity: 87,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/119/200/300',
    pageLink: null,
  },
  {
    tagId: 21,
    tagType: 'organisation',
    name: 'Ecsite',
    tagLine: 'The European Network for Science Centres and Museums',
    country: null,
    popularity: 77,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/120/200/300',
    pageLink: null,
  },
  {
    tagId: 22,
    tagType: 'organisation',
    name: 'EIC',
    tagLine: 'European Innovation Council',
    country: null,
    popularity: 86,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/121/200/300',
    pageLink: null,
  },
  {
    tagId: 23,
    tagType: 'organisation',
    name: 'Elektrotehnicki Fakultet Univerzitet u Beogradu',
    tagLine: null,
    country: null,
    popularity: 7,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/122/200/300',
    pageLink: null,
  },
  {
    tagId: 24,
    tagType: 'organisation',
    name: 'Ellinogermaniki Agogi',
    tagLine: null,
    country: null,
    popularity: 46,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/123/200/300',
    pageLink: null,
  },
  {
    tagId: 25,
    tagType: 'organisation',
    name: 'Engineering – Ingegneria Informatica Spa',
    tagLine: null,
    country: null,
    popularity: 46,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/124/200/300',
    pageLink: null,
  },
  {
    tagId: 26,
    tagType: 'organisation',
    name: 'ESHA',
    tagLine: null,
    country: null,
    popularity: 26,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/125/200/300',
    pageLink: null,
  },
  {
    tagId: 27,
    tagType: 'organisation',
    name: 'European Commission',
    tagLine: null,
    country: null,
    popularity: 83,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/126/200/300',
    pageLink: null,
  },
  {
    tagId: 28,
    tagType: 'organisation',
    name: 'European Commission, Research and innovation, Policy Support Facility',
    tagLine: null,
    country: null,
    popularity: 30,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/127/200/300',
    pageLink: null,
  },
  {
    tagId: 29,
    tagType: 'organisation',
    name: 'European Committee of the Regions',
    tagLine: null,
    country: null,
    popularity: 1,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/128/200/300',
    pageLink: null,
  },
  {
    tagId: 30,
    tagType: 'organisation',
    name: 'European Court of Auditors',
    tagLine: null,
    country: null,
    popularity: 10,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/129/200/300',
    pageLink: null,
  },
  {
    tagId: 31,
    tagType: 'organisation',
    name: 'European Cultural Foundation',
    tagLine: null,
    country: null,
    popularity: 78,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/130/200/300',
    pageLink: null,
  },
  {
    tagId: 32,
    tagType: 'organisation',
    name: 'European Economic and Social Committee',
    tagLine: null,
    country: null,
    popularity: 23,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/131/200/300',
    pageLink: null,
  },
  {
    tagId: 33,
    tagType: 'organisation',
    name: 'European Investment Bank',
    tagLine: null,
    country: null,
    popularity: 41,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/132/200/300',
    pageLink: null,
  },
  {
    tagId: 34,
    tagType: 'organisation',
    name: 'European Parliament',
    tagLine: null,
    country: null,
    popularity: 96,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/133/200/300',
    pageLink: null,
  },
  {
    tagId: 35,
    tagType: 'organisation',
    name: 'European Union External Action Service',
    tagLine: null,
    country: null,
    popularity: 13,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/134/200/300',
    pageLink: null,
  },
  {
    tagId: 36,
    tagType: 'organisation',
    name: 'European Union Institute for Security Studies',
    tagLine: null,
    country: null,
    popularity: 63,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/135/200/300',
    pageLink: null,
  },
  {
    tagId: 37,
    tagType: 'organisation',
    name: 'Eutropian',
    tagLine: null,
    country: null,
    popularity: 5,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/136/200/300',
    pageLink: null,
  },
  {
    tagId: 38,
    tagType: 'organisation',
    name: 'FCT',
    tagLine: 'Fundacao Para A Ciencia E A Tecnologia',
    country: null,
    popularity: 45,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/137/200/300',
    pageLink: null,
  },
  {
    tagId: 39,
    tagType: 'organisation',
    name: 'FIBL Europe',
    tagLine: 'Forschungsinstitutfur Biologischen Landbau in Europa',
    country: null,
    popularity: 46,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/138/200/300',
    pageLink: null,
  },
  {
    tagId: 40,
    tagType: 'organisation',
    name: 'Fondation Institut de Recherche pour le Developpement Durable et les Relations Internationales',
    tagLine: null,
    country: null,
    popularity: 18,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/139/200/300',
    pageLink: null,
  },
  {
    tagId: 41,
    tagType: 'organisation',
    name: 'Fondazione Coispa ETS',
    tagLine: null,
    country: null,
    popularity: 87,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/140/200/300',
    pageLink: null,
  },
  {
    tagId: 42,
    tagType: 'organisation',
    name: 'formicablu',
    tagLine: null,
    country: null,
    popularity: 44,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/141/200/300',
    pageLink: null,
  },
  {
    tagId: 43,
    tagType: 'organisation',
    name: 'Forschungsinstitut fur Biologischen Landbau Stiftung',
    tagLine: null,
    country: null,
    popularity: 77,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/142/200/300',
    pageLink: null,
  },
  {
    tagId: 44,
    tagType: 'organisation',
    name: 'Fraunhofer',
    tagLine:
      'Fraunhofer Gesellschaft Zur Forderung Der Angewandten Forschung EV',
    country: null,
    popularity: 85,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/143/200/300',
    pageLink: null,
  },
  {
    tagId: 45,
    tagType: 'organisation',
    name: 'Fraunhofer ISI',
    tagLine: null,
    country: null,
    popularity: 87,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/144/200/300',
    pageLink: null,
  },
  {
    tagId: 46,
    tagType: 'organisation',
    name: 'Fundacion Zaragoza Logistics Center',
    tagLine: null,
    country: null,
    popularity: 34,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/145/200/300',
    pageLink: null,
  },
  {
    tagId: 47,
    tagType: 'organisation',
    name: 'Future Based',
    tagLine: null,
    country: null,
    popularity: 11,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/146/200/300',
    pageLink: null,
  },
  {
    tagId: 48,
    tagType: 'organisation',
    name: 'Futures Probes',
    tagLine: null,
    country: null,
    popularity: 25,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/147/200/300',
    pageLink: null,
  },
  {
    tagId: 49,
    tagType: 'organisation',
    name: 'Futures2all',
    tagLine: null,
    country: null,
    popularity: 78,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/148/200/300',
    pageLink: null,
  },
  {
    tagId: 50,
    tagType: 'organisation',
    name: 'Futurlab',
    tagLine: null,
    country: null,
    popularity: 52,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/149/200/300',
    pageLink: null,
  },
  {
    tagId: 51,
    tagType: 'organisation',
    name: 'G.A.C. Group',
    tagLine: null,
    country: null,
    popularity: 47,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/150/200/300',
    pageLink: null,
  },
  {
    tagId: 52,
    tagType: 'organisation',
    name: 'Gdansk (Municipality?)',
    tagLine: null,
    country: null,
    popularity: 76,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/151/200/300',
    pageLink: null,
  },
  {
    tagId: 53,
    tagType: 'organisation',
    name: 'German Federal Ministry for Economic Cooperation and Development',
    tagLine: 'BMZ',
    country: 'Germany',
    popularity: 14,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/152/200/300',
    pageLink: null,
  },
  {
    tagId: 54,
    tagType: 'organisation',
    name: 'GIZ',
    tagLine: 'Gesellschaft für Internationale Zusammenarbeit GmbH',
    country: null,
    popularity: 10,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/153/200/300',
    pageLink: null,
  },
  {
    tagId: 55,
    tagType: 'organisation',
    name: 'GLUON',
    tagLine: null,
    country: null,
    popularity: 38,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/154/200/300',
    pageLink: null,
  },
  {
    tagId: 56,
    tagType: 'organisation',
    name: 'i2CAT',
    tagLine: null,
    country: null,
    popularity: 30,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/155/200/300',
    pageLink: null,
  },
  {
    tagId: 57,
    tagType: 'organisation',
    name: 'IFI',
    tagLine: 'Insight Foresight Institute SL',
    country: null,
    popularity: 48,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/156/200/300',
    pageLink: null,
  },
  {
    tagId: 58,
    tagType: 'organisation',
    name: 'INL',
    tagLine: 'International Iberian Nanotechnology Laboratory',
    country: null,
    popularity: 93,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/157/200/300',
    pageLink: null,
  },
  {
    tagId: 59,
    tagType: 'organisation',
    name: 'Innovationscenter for Okologisk Landbrug P/S',
    tagLine: null,
    country: null,
    popularity: 59,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/158/200/300',
    pageLink: null,
  },
  {
    tagId: 60,
    tagType: 'organisation',
    name: 'INRAE',
    tagLine:
      "Institut National De Recherche Pour L'agriculture, L'alimentation Et L'environnement",
    country: null,
    popularity: 4,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/159/200/300',
    pageLink: null,
  },
  {
    tagId: 61,
    tagType: 'organisation',
    name: 'INSEC TEC',
    tagLine:
      'Instituto de Engenhariade Sistemas e Computadores, Tecnologia e Ciencia',
    country: null,
    popularity: 14,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/160/200/300',
    pageLink: null,
  },
  {
    tagId: 62,
    tagType: 'organisation',
    name: 'Institut Technique de l Agriculture Biologique',
    tagLine: null,
    country: null,
    popularity: 91,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/161/200/300',
    pageLink: null,
  },
  {
    tagId: 63,
    tagType: 'organisation',
    name: 'International Federation of Organic Agriculture Movements European Union Regional Group',
    tagLine: null,
    country: null,
    popularity: 69,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/162/200/300',
    pageLink: null,
  },
  {
    tagId: 64,
    tagType: 'organisation',
    name: 'Iris Technology Solutions Sociedad Limitada',
    tagLine: null,
    country: null,
    popularity: 27,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/163/200/300',
    pageLink: null,
  },
  {
    tagId: 65,
    tagType: 'organisation',
    name: 'Johann Heinrich Von Thuenen-Institut, Bundesforschungsinstitut Fuer Laendliche Raeume, Wald und Fischerei',
    tagLine: null,
    country: null,
    popularity: 14,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/164/200/300',
    pageLink: null,
  },
  {
    tagId: 66,
    tagType: 'organisation',
    name: 'Joint Research Center',
    tagLine: null,
    country: null,
    popularity: 64,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/165/200/300',
    pageLink: null,
  },
  {
    tagId: 67,
    tagType: 'organisation',
    name: 'JRC',
    tagLine: 'European Commission Joint Research Centre',
    country: null,
    popularity: 59,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/166/200/300',
    pageLink: null,
  },
  {
    tagId: 68,
    tagType: 'organisation',
    name: 'Junior Academy of Sciences of Ukraine',
    tagLine: null,
    country: 'Ukraine',
    popularity: 53,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/167/200/300',
    pageLink: null,
  },
  {
    tagId: 69,
    tagType: 'organisation',
    name: 'Kaunas University of Technology',
    tagLine: null,
    country: null,
    popularity: 96,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/168/200/300',
    pageLink: null,
  },
  {
    tagId: 70,
    tagType: 'organisation',
    name: 'Kultura Nova Foundation',
    tagLine: null,
    country: null,
    popularity: 75,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/169/200/300',
    pageLink: null,
  },
  {
    tagId: 71,
    tagType: 'organisation',
    name: 'Landwirtschaftskammer Niederoesterreich',
    tagLine: null,
    country: null,
    popularity: 89,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/170/200/300',
    pageLink: null,
  },
  {
    tagId: 72,
    tagType: 'organisation',
    name: 'Lisbon Council for Economic Competitiveness',
    tagLine: null,
    country: null,
    popularity: 11,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/171/200/300',
    pageLink: null,
  },
  {
    tagId: 73,
    tagType: 'organisation',
    name: 'LUISS',
    tagLine: null,
    country: null,
    popularity: 93,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/172/200/300',
    pageLink: null,
  },
  {
    tagId: 74,
    tagType: 'organisation',
    name: 'MADE SCARL',
    tagLine: null,
    country: null,
    popularity: 71,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/173/200/300',
    pageLink: null,
  },
  {
    tagId: 75,
    tagType: 'organisation',
    name: 'Metaculus',
    tagLine: 'online forecasting platform and aggregation engine',
    country: null,
    popularity: 12,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/174/200/300',
    pageLink: null,
  },
  {
    tagId: 76,
    tagType: 'organisation',
    name: 'Ministry of Labour and Social Affairs from Czech Republic',
    tagLine: null,
    country: null,
    popularity: 50,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/175/200/300',
    pageLink: null,
  },
  {
    tagId: 77,
    tagType: 'organisation',
    name: 'MitOst e.V.',
    tagLine: null,
    country: null,
    popularity: 57,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/176/200/300',
    pageLink: null,
  },
  {
    tagId: 78,
    tagType: 'organisation',
    name: 'Modem',
    tagLine: null,
    country: null,
    popularity: 41,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/177/200/300',
    pageLink: null,
  },
  {
    tagId: 79,
    tagType: 'organisation',
    name: 'NATURLAND',
    tagLine: 'Verband fur Okologischen Landbau Ev',
    country: null,
    popularity: 85,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/178/200/300',
    pageLink: null,
  },
  {
    tagId: 80,
    tagType: 'organisation',
    name: 'Normals',
    tagLine: null,
    country: null,
    popularity: 13,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/179/200/300',
    pageLink: null,
  },
  {
    tagId: 81,
    tagType: 'organisation',
    name: 'Okologiai Mezogazdasagi Kutatointezet Kozhasznu Nonprofit Kft',
    tagLine: null,
    country: null,
    popularity: 97,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/180/200/300',
    pageLink: null,
  },
  {
    tagId: 82,
    tagType: 'organisation',
    name: 'PAL Robotics SL',
    tagLine: null,
    country: null,
    popularity: 29,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/181/200/300',
    pageLink: null,
  },
  {
    tagId: 83,
    tagType: 'organisation',
    name: 'Panteion',
    tagLine: null,
    country: null,
    popularity: 89,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/182/200/300',
    pageLink: null,
  },
  {
    tagId: 84,
    tagType: 'organisation',
    name: 'People’s Voice Media',
    tagLine: null,
    country: null,
    popularity: 74,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/183/200/300',
    pageLink: null,
  },
  {
    tagId: 85,
    tagType: 'organisation',
    name: 'Policy Lab',
    tagLine: null,
    country: null,
    popularity: 44,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/184/200/300',
    pageLink: null,
  },
  {
    tagId: 86,
    tagType: 'organisation',
    name: 'Politecnico di Milano',
    tagLine: null,
    country: 'Italy',
    popularity: 22,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/185/200/300',
    pageLink: null,
  },
  {
    tagId: 87,
    tagType: 'organisation',
    name: 'Prasidentenkonferenz der Landwirtschaftskammern Osterreichs',
    tagLine: null,
    country: null,
    popularity: 81,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/186/200/300',
    pageLink: null,
  },
  {
    tagId: 88,
    tagType: 'organisation',
    name: 'Prospectiva',
    tagLine: 'Asociația Institutul de Prospectivă',
    country: 'Romania',
    popularity: 74,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/187/200/300',
    pageLink: null,
  },
  {
    tagId: 89,
    tagType: 'organisation',
    name: 'PROSPER Network',
    tagLine: null,
    country: null,
    popularity: 44,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/188/200/300',
    pageLink: null,
  },
  {
    tagId: 90,
    tagType: 'organisation',
    name: 'RWI',
    tagLine: 'Leibniz Institut fur Wirtschaftsforschung e.V.',
    country: null,
    popularity: 67,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/189/200/300',
    pageLink: null,
  },
  {
    tagId: 91,
    tagType: 'organisation',
    name: 'S. Mantzanakis KAI SIA O.E (Helenos)',
    tagLine: null,
    country: null,
    popularity: 84,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/190/200/300',
    pageLink: null,
  },
  {
    tagId: 92,
    tagType: 'organisation',
    name: 'Science View',
    tagLine: null,
    country: null,
    popularity: 74,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/191/200/300',
    pageLink: null,
  },
  {
    tagId: 93,
    tagType: 'organisation',
    name: 'STAM',
    tagLine: null,
    country: null,
    popularity: 1,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/192/200/300',
    pageLink: null,
  },
  {
    tagId: 94,
    tagType: 'organisation',
    name: 'SWPS University',
    tagLine: 'University of Social Sciences and Humanities',
    country: null,
    popularity: 89,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/193/200/300',
    pageLink: null,
  },
  {
    tagId: 95,
    tagType: 'organisation',
    name: 'TC Praha',
    tagLine: 'Technologicke Centrum Praha ZSPO',
    country: null,
    popularity: 65,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/194/200/300',
    pageLink: null,
  },
  {
    tagId: 96,
    tagType: 'organisation',
    name: 'Teach the Future',
    tagLine: null,
    country: null,
    popularity: 71,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/195/200/300',
    pageLink: null,
  },
  {
    tagId: 97,
    tagType: 'organisation',
    name: 'Technische Universiteit Eindhoven',
    tagLine: null,
    country: null,
    popularity: 97,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/196/200/300',
    pageLink: null,
  },
  {
    tagId: 98,
    tagType: 'organisation',
    name: 'Technopolis',
    tagLine: null,
    country: null,
    popularity: 81,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/197/200/300',
    pageLink: null,
  },
  {
    tagId: 99,
    tagType: 'organisation',
    name: 'The Department of Socio-Economic Geography at the University of Gdansk',
    tagLine: null,
    country: null,
    popularity: 11,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/198/200/300',
    pageLink: null,
  },
  {
    tagId: 100,
    tagType: 'organisation',
    name: 'The Futures Literacy Company',
    tagLine: null,
    country: null,
    popularity: 16,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/199/200/300',
    pageLink: null,
  },
  {
    tagId: 101,
    tagType: 'organisation',
    name: 'The Municipality of Reggio Emilia',
    tagLine: null,
    country: null,
    popularity: 58,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/200/200/300',
    pageLink: null,
  },
  {
    tagId: 102,
    tagType: 'organisation',
    name: 'The University of Bologna',
    tagLine: 'UNIBO',
    country: null,
    popularity: 31,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/201/200/300',
    pageLink: null,
  },
  {
    tagId: 103,
    tagType: 'organisation',
    name: 'The University of Helsinki',
    tagLine: null,
    country: null,
    popularity: 25,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/202/200/300',
    pageLink: null,
  },
  {
    tagId: 104,
    tagType: 'organisation',
    name: 'The University of Manchester',
    tagLine: null,
    country: null,
    popularity: 63,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/203/200/300',
    pageLink: null,
  },
  {
    tagId: 105,
    tagType: 'organisation',
    name: 'Tipi',
    tagLine: null,
    country: null,
    popularity: 24,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/204/200/300',
    pageLink: null,
  },
  {
    tagId: 106,
    tagType: 'organisation',
    name: 'Turun Yliopisto',
    tagLine: 'UTU',
    country: 'Finland',
    popularity: 27,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/205/200/300',
    pageLink: null,
  },
  {
    tagId: 107,
    tagType: 'organisation',
    name: 'UEFISCDI',
    tagLine:
      'Unitatea Executivă pentru Finanțarea Învățământului Superior, a Cercetării, Dezvoltării și Inovării',
    country: 'Romania',
    popularity: 26,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/206/200/300',
    pageLink: null,
  },
  {
    tagId: 108,
    tagType: 'organisation',
    name: 'Universidad de la Iglesia de Deusto Entidad Religiosa',
    tagLine: null,
    country: null,
    popularity: 35,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/207/200/300',
    pageLink: null,
  },
  {
    tagId: 109,
    tagType: 'organisation',
    name: 'Universita degli Studi di Padova',
    tagLine: null,
    country: null,
    popularity: 13,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/208/200/300',
    pageLink: null,
  },
  {
    tagId: 110,
    tagType: 'organisation',
    name: 'Universita Politecnica delle Marche',
    tagLine: null,
    country: null,
    popularity: 63,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/209/200/300',
    pageLink: null,
  },
  {
    tagId: 111,
    tagType: 'organisation',
    name: 'Universitat de Barcelona',
    tagLine: null,
    country: null,
    popularity: 31,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/210/200/300',
    pageLink: null,
  },
  {
    tagId: 112,
    tagType: 'organisation',
    name: 'Universitatea Spiru Haret',
    tagLine: null,
    country: 'Romania',
    popularity: 23,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/211/200/300',
    pageLink: null,
  },
  {
    tagId: 113,
    tagType: 'organisation',
    name: 'University College Dublin, National University of Ireland, Dublin',
    tagLine: null,
    country: 'Ireland',
    popularity: 59,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/212/200/300',
    pageLink: null,
  },
  {
    tagId: 114,
    tagType: 'organisation',
    name: 'University of Eastern Finland',
    tagLine: null,
    country: 'Finland',
    popularity: 97,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/213/200/300',
    pageLink: null,
  },
  {
    tagId: 115,
    tagType: 'organisation',
    name: 'University of Exeter',
    tagLine: null,
    country: null,
    popularity: 7,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/214/200/300',
    pageLink: null,
  },
  {
    tagId: 116,
    tagType: 'organisation',
    name: 'University of Malta',
    tagLine: null,
    country: null,
    popularity: 4,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/215/200/300',
    pageLink: null,
  },
  {
    tagId: 117,
    tagType: 'organisation',
    name: 'University of Oxford',
    tagLine: null,
    country: null,
    popularity: 78,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/216/200/300',
    pageLink: null,
  },
  {
    tagId: 118,
    tagType: 'organisation',
    name: 'UV SR',
    tagLine: 'Urad Vlady Slovenskej Republiky',
    country: null,
    popularity: 27,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/217/200/300',
    pageLink: null,
  },
  {
    tagId: 119,
    tagType: 'organisation',
    name: 'VDI/VDE IT',
    tagLine: 'VDI/VDE Innovation + Technik GmbH',
    country: null,
    popularity: 87,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/218/200/300',
    pageLink: null,
  },
  {
    tagId: 120,
    tagType: 'organisation',
    name: 'VTT',
    tagLine: null,
    country: null,
    popularity: 29,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/219/200/300',
    pageLink: null,
  },
  {
    tagId: 121,
    tagType: 'organisation',
    name: 'ZSI',
    tagLine: 'Centre for Social Innovation',
    country: null,
    popularity: 78,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/220/200/300',
    pageLink: null,
  },
  {
    tagId: 1,
    tagType: 'person',
    name: 'Albert Bravo-Biosca',
    tagLine: null,
    country: null,
    popularity: 83,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/100/200/300',
    pageLink: null,
  },
  {
    tagId: 2,
    tagType: 'person',
    name: 'Albert Norström',
    tagLine: null,
    country: null,
    popularity: 72,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/101/200/300',
    pageLink: null,
  },
  {
    tagId: 3,
    tagType: 'person',
    name: 'Alexandre Reznikow',
    tagLine: null,
    country: null,
    popularity: 7,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/102/200/300',
    pageLink: null,
  },
  {
    tagId: 4,
    tagType: 'person',
    name: 'Alexandrova-Stefanova N.',
    tagLine: null,
    country: null,
    popularity: 56,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/103/200/300',
    pageLink: null,
  },
  {
    tagId: 5,
    tagType: 'person',
    name: 'Attila Havas',
    tagLine: null,
    country: null,
    popularity: 30,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/104/200/300',
    pageLink: null,
  },
  {
    tagId: 6,
    tagType: 'person',
    name: 'Audouin S.',
    tagLine: null,
    country: null,
    popularity: 40,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/105/200/300',
    pageLink: null,
  },
  {
    tagId: 7,
    tagType: 'person',
    name: 'Aureli Soria-Frisch',
    tagLine: null,
    country: null,
    popularity: 10,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/106/200/300',
    pageLink: null,
  },
  {
    tagId: 8,
    tagType: 'person',
    name: 'Benjamin Sovacool',
    tagLine: null,
    country: null,
    popularity: 39,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/107/200/300',
    pageLink: null,
  },
  {
    tagId: 9,
    tagType: 'person',
    name: 'Bianca Dragomir',
    tagLine: null,
    country: 'Romania',
    popularity: 71,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/108/200/300',
    pageLink: null,
  },
  {
    tagId: 10,
    tagType: 'person',
    name: 'Brigita Jurisic',
    tagLine: null,
    country: null,
    popularity: 64,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/109/200/300',
    pageLink: null,
  },
  {
    tagId: 11,
    tagType: 'person',
    name: 'Bruna De Marchi',
    tagLine: null,
    country: null,
    popularity: 95,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/110/200/300',
    pageLink: null,
  },
  {
    tagId: 12,
    tagType: 'person',
    name: 'Carsten Claus',
    tagLine: null,
    country: null,
    popularity: 57,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/111/200/300',
    pageLink: null,
  },
  {
    tagId: 13,
    tagType: 'person',
    name: 'Catalina Martinez',
    tagLine: null,
    country: null,
    popularity: 44,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/112/200/300',
    pageLink: null,
  },
  {
    tagId: 14,
    tagType: 'person',
    name: 'Corina Murafa',
    tagLine: null,
    country: null,
    popularity: 70,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/113/200/300',
    pageLink: null,
  },
  {
    tagId: 15,
    tagType: 'person',
    name: 'Cristiano Cagnin',
    tagLine: null,
    country: null,
    popularity: 43,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/114/200/300',
    pageLink: null,
  },
  {
    tagId: 16,
    tagType: 'person',
    name: 'Dana Wasserbacher',
    tagLine: null,
    country: null,
    popularity: 73,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/115/200/300',
    pageLink: null,
  },
  {
    tagId: 17,
    tagType: 'person',
    name: 'Daouia Chalali',
    tagLine: null,
    country: null,
    popularity: 5,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/116/200/300',
    pageLink: null,
  },
  {
    tagId: 18,
    tagType: 'person',
    name: 'Dave Shaw',
    tagLine: null,
    country: null,
    popularity: 57,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/117/200/300',
    pageLink: null,
  },
  {
    tagId: 19,
    tagType: 'person',
    name: 'Djamen P.',
    tagLine: null,
    country: null,
    popularity: 61,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/118/200/300',
    pageLink: null,
  },
  {
    tagId: 20,
    tagType: 'person',
    name: 'Dominik Hajduk',
    tagLine: null,
    country: null,
    popularity: 23,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/119/200/300',
    pageLink: null,
  },
  {
    tagId: 21,
    tagType: 'person',
    name: 'Duncan McLaren',
    tagLine: null,
    country: null,
    popularity: 74,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/120/200/300',
    pageLink: null,
  },
  {
    tagId: 22,
    tagType: 'person',
    name: 'Edina Löhr',
    tagLine: null,
    country: null,
    popularity: 18,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/121/200/300',
    pageLink: null,
  },
  {
    tagId: 23,
    tagType: 'person',
    name: 'Elena Artiles Leyes',
    tagLine: null,
    country: null,
    popularity: 12,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/122/200/300',
    pageLink: null,
  },
  {
    tagId: 24,
    tagType: 'person',
    name: 'Enric Bas',
    tagLine: null,
    country: null,
    popularity: 11,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/123/200/300',
    pageLink: null,
  },
  {
    tagId: 25,
    tagType: 'person',
    name: 'Erica Bol',
    tagLine: null,
    country: null,
    popularity: 90,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/124/200/300',
    pageLink: null,
  },
  {
    tagId: 26,
    tagType: 'person',
    name: 'Fanny Lalot',
    tagLine: null,
    country: null,
    popularity: 95,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/125/200/300',
    pageLink: null,
  },
  {
    tagId: 27,
    tagType: 'person',
    name: 'Finn Speijer',
    tagLine: null,
    country: null,
    popularity: 28,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/126/200/300',
    pageLink: null,
  },
  {
    tagId: 28,
    tagType: 'person',
    name: 'Florian Roth',
    tagLine: null,
    country: null,
    popularity: 50,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/127/200/300',
    pageLink: null,
  },
  {
    tagId: 29,
    tagType: 'person',
    name: 'Francesco Mureddu',
    tagLine: null,
    country: null,
    popularity: 69,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/128/200/300',
    pageLink: null,
  },
  {
    tagId: 30,
    tagType: 'person',
    name: 'Giovanna Guiffrè',
    tagLine: null,
    country: null,
    popularity: 93,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/129/200/300',
    pageLink: null,
  },
  {
    tagId: 31,
    tagType: 'person',
    name: 'Hayley Trowbridge',
    tagLine: null,
    country: null,
    popularity: 70,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/130/200/300',
    pageLink: null,
  },
  {
    tagId: 32,
    tagType: 'person',
    name: 'Heila Lotz-Sisitka',
    tagLine: null,
    country: null,
    popularity: 5,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/131/200/300',
    pageLink: null,
  },
  {
    tagId: 33,
    tagType: 'person',
    name: 'Holger Nitsch',
    tagLine: null,
    country: null,
    popularity: 73,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/132/200/300',
    pageLink: null,
  },
  {
    tagId: 34,
    tagType: 'person',
    name: 'Hywel Jones',
    tagLine: null,
    country: null,
    popularity: 3,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/133/200/300',
    pageLink: null,
  },
  {
    tagId: 35,
    tagType: 'person',
    name: 'Jennifer Gidley',
    tagLine: null,
    country: null,
    popularity: 51,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/134/200/300',
    pageLink: null,
  },
  {
    tagId: 36,
    tagType: 'person',
    name: 'Kathrine Jensen',
    tagLine: null,
    country: null,
    popularity: 63,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/135/200/300',
    pageLink: null,
  },
  {
    tagId: 37,
    tagType: 'person',
    name: 'Katrina Günther',
    tagLine: null,
    country: null,
    popularity: 52,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/136/200/300',
    pageLink: null,
  },
  {
    tagId: 38,
    tagType: 'person',
    name: 'Kerstin Cuhls',
    tagLine: null,
    country: null,
    popularity: 19,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/137/200/300',
    pageLink: null,
  },
  {
    tagId: 39,
    tagType: 'person',
    name: 'Kezia Barker',
    tagLine: null,
    country: null,
    popularity: 80,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/138/200/300',
    pageLink: null,
  },
  {
    tagId: 40,
    tagType: 'person',
    name: 'Knut Blind',
    tagLine: null,
    country: null,
    popularity: 6,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/139/200/300',
    pageLink: null,
  },
  {
    tagId: 41,
    tagType: 'person',
    name: 'Kolos N.',
    tagLine: null,
    country: null,
    popularity: 1,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/140/200/300',
    pageLink: null,
  },
  {
    tagId: 42,
    tagType: 'person',
    name: 'Laura Galante',
    tagLine: null,
    country: null,
    popularity: 42,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/141/200/300',
    pageLink: null,
  },
  {
    tagId: 43,
    tagType: 'person',
    name: 'Leena Sarvaranta',
    tagLine: null,
    country: null,
    popularity: 39,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/142/200/300',
    pageLink: null,
  },
  {
    tagId: 44,
    tagType: 'person',
    name: 'Lourdes Rodriguez',
    tagLine: null,
    country: null,
    popularity: 55,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/143/200/300',
    pageLink: null,
  },
  {
    tagId: 45,
    tagType: 'person',
    name: 'Luk Van Langenhove',
    tagLine: null,
    country: null,
    popularity: 41,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/144/200/300',
    pageLink: null,
  },
  {
    tagId: 46,
    tagType: 'person',
    name: 'Lukas Jung',
    tagLine: null,
    country: null,
    popularity: 6,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/145/200/300',
    pageLink: null,
  },
  {
    tagId: 47,
    tagType: 'person',
    name: 'Luke Georghiou',
    tagLine: null,
    country: null,
    popularity: 26,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/146/200/300',
    pageLink: null,
  },
  {
    tagId: 48,
    tagType: 'person',
    name: 'Maciej Jagaciak',
    tagLine: null,
    country: null,
    popularity: 85,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/147/200/300',
    pageLink: null,
  },
  {
    tagId: 49,
    tagType: 'person',
    name: 'Maciej Krzysztofowicz',
    tagLine: null,
    country: null,
    popularity: 88,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/148/200/300',
    pageLink: null,
  },
  {
    tagId: 50,
    tagType: 'person',
    name: 'Maija Knutti',
    tagLine: null,
    country: null,
    popularity: 91,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/149/200/300',
    pageLink: null,
  },
  {
    tagId: 51,
    tagType: 'person',
    name: 'Marco Letizi',
    tagLine: null,
    country: null,
    popularity: 2,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/150/200/300',
    pageLink: null,
  },
  {
    tagId: 52,
    tagType: 'person',
    name: 'Marina Dias',
    tagLine: null,
    country: null,
    popularity: 53,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/151/200/300',
    pageLink: null,
  },
  {
    tagId: 53,
    tagType: 'person',
    name: 'Marjolein Caniels',
    tagLine: null,
    country: null,
    popularity: 12,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/152/200/300',
    pageLink: null,
  },
  {
    tagId: 54,
    tagType: 'person',
    name: 'Marta Jalšovec',
    tagLine: null,
    country: null,
    popularity: 58,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/153/200/300',
    pageLink: null,
  },
  {
    tagId: 55,
    tagType: 'person',
    name: 'Masafumi Nishi',
    tagLine: null,
    country: null,
    popularity: 17,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/154/200/300',
    pageLink: null,
  },
  {
    tagId: 56,
    tagType: 'person',
    name: 'Matthias Weber',
    tagLine: null,
    country: null,
    popularity: 11,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/155/200/300',
    pageLink: null,
  },
  {
    tagId: 57,
    tagType: 'person',
    name: 'Matti Minkkinena',
    tagLine: null,
    country: null,
    popularity: 80,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/156/200/300',
    pageLink: null,
  },
  {
    tagId: 58,
    tagType: 'person',
    name: 'Michal Pazour',
    tagLine: null,
    country: null,
    popularity: 25,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/157/200/300',
    pageLink: null,
  },
  {
    tagId: 59,
    tagType: 'person',
    name: 'Mike Parr',
    tagLine: null,
    country: null,
    popularity: 41,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/158/200/300',
    pageLink: null,
  },
  {
    tagId: 60,
    tagType: 'person',
    name: 'Mikkel Knudsen',
    tagLine: null,
    country: null,
    popularity: 16,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/159/200/300',
    pageLink: null,
  },
  {
    tagId: 61,
    tagType: 'person',
    name: 'Mirko Boehm',
    tagLine: null,
    country: null,
    popularity: 81,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/160/200/300',
    pageLink: null,
  },
  {
    tagId: 62,
    tagType: 'person',
    name: 'Moritz Hunger',
    tagLine: null,
    country: null,
    popularity: 81,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/161/200/300',
    pageLink: null,
  },
  {
    tagId: 63,
    tagType: 'person',
    name: 'Mroczek Z.K.',
    tagLine: null,
    country: null,
    popularity: 1,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/162/200/300',
    pageLink: null,
  },
  {
    tagId: 64,
    tagType: 'person',
    name: 'Norbert Kołos',
    tagLine: null,
    country: null,
    popularity: 32,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/163/200/300',
    pageLink: null,
  },
  {
    tagId: 65,
    tagType: 'person',
    name: 'Nosarzewski K.',
    tagLine: null,
    country: null,
    popularity: 26,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/164/200/300',
    pageLink: null,
  },
  {
    tagId: 66,
    tagType: 'person',
    name: 'Ollie Bream McIntosh',
    tagLine: null,
    country: null,
    popularity: 92,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/165/200/300',
    pageLink: null,
  },
  {
    tagId: 67,
    tagType: 'person',
    name: 'Peter Dickinson',
    tagLine: null,
    country: null,
    popularity: 94,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/166/200/300',
    pageLink: null,
  },
  {
    tagId: 68,
    tagType: 'person',
    name: 'Peter Lund',
    tagLine: null,
    country: null,
    popularity: 93,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/167/200/300',
    pageLink: null,
  },
  {
    tagId: 69,
    tagType: 'person',
    name: 'Philine Warnke',
    tagLine: null,
    country: null,
    popularity: 65,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/168/200/300',
    pageLink: null,
  },
  {
    tagId: 70,
    tagType: 'person',
    name: 'Radu Gheorghiu',
    tagLine: null,
    country: 'Romania',
    popularity: 80,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/169/200/300',
    pageLink: null,
  },
  {
    tagId: 71,
    tagType: 'person',
    name: 'Rainer Quitzow',
    tagLine: null,
    country: null,
    popularity: 54,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/170/200/300',
    pageLink: null,
  },
  {
    tagId: 72,
    tagType: 'person',
    name: 'Renata Mandzhieva',
    tagLine: null,
    country: null,
    popularity: 25,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/171/200/300',
    pageLink: null,
  },
  {
    tagId: 73,
    tagType: 'person',
    name: 'Rene von Schomberg',
    tagLine: null,
    country: null,
    popularity: 85,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/172/200/300',
    pageLink: null,
  },
  {
    tagId: 74,
    tagType: 'person',
    name: 'Ron Oren',
    tagLine: null,
    country: null,
    popularity: 74,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/173/200/300',
    pageLink: null,
  },
  {
    tagId: 75,
    tagType: 'person',
    name: 'Rosanna Fornasiero',
    tagLine: null,
    country: null,
    popularity: 15,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/174/200/300',
    pageLink: null,
  },
  {
    tagId: 76,
    tagType: 'person',
    name: 'Sabine Hafner-Zimmermann',
    tagLine: null,
    country: null,
    popularity: 46,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/175/200/300',
    pageLink: null,
  },
  {
    tagId: 77,
    tagType: 'person',
    name: 'Sandro Mendonça',
    tagLine: null,
    country: null,
    popularity: 66,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/176/200/300',
    pageLink: null,
  },
  {
    tagId: 78,
    tagType: 'person',
    name: 'Sanna Ahvenharjua',
    tagLine: null,
    country: null,
    popularity: 34,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/177/200/300',
    pageLink: null,
  },
  {
    tagId: 79,
    tagType: 'person',
    name: 'Simon Schmitz',
    tagLine: null,
    country: null,
    popularity: 22,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/178/200/300',
    pageLink: null,
  },
  {
    tagId: 80,
    tagType: 'person',
    name: 'Simone Weske',
    tagLine: null,
    country: null,
    popularity: 17,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/179/200/300',
    pageLink: null,
  },
  {
    tagId: 81,
    tagType: 'person',
    name: 'Sirkku Juhola',
    tagLine: null,
    country: null,
    popularity: 31,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/180/200/300',
    pageLink: null,
  },
  {
    tagId: 82,
    tagType: 'person',
    name: 'Susanne Giesecke',
    tagLine: null,
    country: null,
    popularity: 37,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/181/200/300',
    pageLink: null,
  },
  {
    tagId: 83,
    tagType: 'person',
    name: 'Tanja Schindler',
    tagLine: null,
    country: null,
    popularity: 12,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/182/200/300',
    pageLink: null,
  },
  {
    tagId: 84,
    tagType: 'person',
    name: 'Tatiana Efremenko',
    tagLine: null,
    country: null,
    popularity: 78,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/183/200/300',
    pageLink: null,
  },
  {
    tagId: 85,
    tagType: 'person',
    name: 'Totti Könnölä',
    tagLine: null,
    country: null,
    popularity: 57,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/184/200/300',
    pageLink: null,
  },
  {
    tagId: 86,
    tagType: 'person',
    name: 'Ulli Lorenz',
    tagLine: null,
    country: null,
    popularity: 12,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/185/200/300',
    pageLink: null,
  },
  {
    tagId: 87,
    tagType: 'person',
    name: 'Umut Turksen',
    tagLine: null,
    country: null,
    popularity: 49,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/186/200/300',
    pageLink: null,
  },
  {
    tagId: 88,
    tagType: 'person',
    name: 'Valentina Malcotti',
    tagLine: null,
    country: null,
    popularity: 18,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/187/200/300',
    pageLink: null,
  },
  {
    tagId: 89,
    tagType: 'person',
    name: 'Wan J.',
    tagLine: null,
    country: null,
    popularity: 14,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/188/200/300',
    pageLink: null,
  },
  {
    tagId: 90,
    tagType: 'person',
    name: 'Wenzel Mehnert',
    tagLine: null,
    country: null,
    popularity: 36,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/189/200/300',
    pageLink: null,
  },
  {
    tagId: 1,
    tagType: 'domain',
    name: 'agriculture',
    tagLine: null,
    country: null,
    popularity: 2,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/100/200/300',
    pageLink: null,
  },
  {
    tagId: 2,
    tagType: 'domain',
    name: 'art',
    tagLine: null,
    country: null,
    popularity: 38,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/101/200/300',
    pageLink: null,
  },
  {
    tagId: 3,
    tagType: 'domain',
    name: 'AI',
    tagLine: 'Artificial Intelligence',
    country: null,
    popularity: 82,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/102/200/300',
    pageLink: null,
  },
  {
    tagId: 4,
    tagType: 'domain',
    name: 'awarness of the present',
    tagLine: null,
    country: null,
    popularity: 65,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/103/200/300',
    pageLink: null,
  },
  {
    tagId: 5,
    tagType: 'domain',
    name: 'big tech',
    tagLine: null,
    country: null,
    popularity: 22,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/104/200/300',
    pageLink: null,
  },
  {
    tagId: 6,
    tagType: 'domain',
    name: 'biodiversity',
    tagLine: null,
    country: null,
    popularity: 36,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/105/200/300',
    pageLink: null,
  },
  {
    tagId: 7,
    tagType: 'domain',
    name: 'circular economy',
    tagLine: null,
    country: null,
    popularity: 93,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/106/200/300',
    pageLink: null,
  },
  {
    tagId: 8,
    tagType: 'domain',
    name: 'citizen engagement',
    tagLine: null,
    country: null,
    popularity: 49,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/107/200/300',
    pageLink: null,
  },
  {
    tagId: 9,
    tagType: 'domain',
    name: 'civic resilience',
    tagLine: null,
    country: null,
    popularity: 90,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/108/200/300',
    pageLink: null,
  },
  {
    tagId: 10,
    tagType: 'domain',
    name: 'climate',
    tagLine: null,
    country: null,
    popularity: 83,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/109/200/300',
    pageLink: null,
  },
  {
    tagId: 11,
    tagType: 'domain',
    name: 'climate change',
    tagLine: null,
    country: null,
    popularity: 38,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/110/200/300',
    pageLink: null,
  },
  {
    tagId: 12,
    tagType: 'domain',
    name: 'coastal areas',
    tagLine: null,
    country: null,
    popularity: 67,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/111/200/300',
    pageLink: null,
  },
  {
    tagId: 13,
    tagType: 'domain',
    name: 'community',
    tagLine: null,
    country: null,
    popularity: 29,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/112/200/300',
    pageLink: null,
  },
  {
    tagId: 14,
    tagType: 'domain',
    name: 'connection to nature',
    tagLine: null,
    country: null,
    popularity: 67,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/113/200/300',
    pageLink: null,
  },
  {
    tagId: 15,
    tagType: 'domain',
    name: 'criminality',
    tagLine: null,
    country: null,
    popularity: 3,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/114/200/300',
    pageLink: null,
  },
  {
    tagId: 16,
    tagType: 'domain',
    name: 'cybersecurity',
    tagLine: null,
    country: null,
    popularity: 12,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/115/200/300',
    pageLink: null,
  },
  {
    tagId: 17,
    tagType: 'domain',
    name: 'data',
    tagLine: null,
    country: null,
    popularity: 22,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/116/200/300',
    pageLink: null,
  },
  {
    tagId: 18,
    tagType: 'domain',
    name: 'democracy',
    tagLine: null,
    country: null,
    popularity: 13,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/117/200/300',
    pageLink: null,
  },
  {
    tagId: 19,
    tagType: 'domain',
    name: 'digital',
    tagLine: null,
    country: null,
    popularity: 73,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/118/200/300',
    pageLink: null,
  },
  {
    tagId: 20,
    tagType: 'domain',
    name: 'digitalisation',
    tagLine: null,
    country: null,
    popularity: 53,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/119/200/300',
    pageLink: null,
  },
  {
    tagId: 21,
    tagType: 'domain',
    name: 'economic crime',
    tagLine: null,
    country: null,
    popularity: 78,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/120/200/300',
    pageLink: null,
  },
  {
    tagId: 22,
    tagType: 'domain',
    name: 'economy',
    tagLine: null,
    country: null,
    popularity: 78,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/121/200/300',
    pageLink: null,
  },
  {
    tagId: 23,
    tagType: 'domain',
    name: 'ecosystems',
    tagLine: null,
    country: null,
    popularity: 63,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/122/200/300',
    pageLink: null,
  },
  {
    tagId: 24,
    tagType: 'domain',
    name: 'education',
    tagLine: null,
    country: null,
    popularity: 54,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/123/200/300',
    pageLink: null,
  },
  {
    tagId: 25,
    tagType: 'domain',
    name: 'emerging technologies',
    tagLine: null,
    country: null,
    popularity: 93,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/124/200/300',
    pageLink: null,
  },
  {
    tagId: 26,
    tagType: 'domain',
    name: 'energy',
    tagLine: null,
    country: null,
    popularity: 37,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/125/200/300',
    pageLink: null,
  },
  {
    tagId: 27,
    tagType: 'domain',
    name: 'ethics',
    tagLine: null,
    country: null,
    popularity: 42,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/126/200/300',
    pageLink: null,
  },
  {
    tagId: 28,
    tagType: 'domain',
    name: 'EU R&I policy',
    tagLine: 'European Union Research and Innovation policy',
    country: null,
    popularity: 62,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/127/200/300',
    pageLink: null,
  },
  {
    tagId: 29,
    tagType: 'domain',
    name: 'fairness',
    tagLine: null,
    country: null,
    popularity: 12,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/128/200/300',
    pageLink: null,
  },
  {
    tagId: 30,
    tagType: 'domain',
    name: 'food',
    tagLine: null,
    country: null,
    popularity: 29,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/129/200/300',
    pageLink: null,
  },
  {
    tagId: 31,
    tagType: 'domain',
    name: 'futures stories',
    tagLine: null,
    country: null,
    popularity: 19,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/130/200/300',
    pageLink: null,
  },
  {
    tagId: 32,
    tagType: 'domain',
    name: 'geoengineering',
    tagLine: null,
    country: null,
    popularity: 86,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/131/200/300',
    pageLink: null,
  },
  {
    tagId: 33,
    tagType: 'domain',
    name: 'geopolitics',
    tagLine: null,
    country: null,
    popularity: 94,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/132/200/300',
    pageLink: null,
  },
  {
    tagId: 34,
    tagType: 'domain',
    name: 'global commons',
    tagLine: null,
    country: null,
    popularity: 97,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/133/200/300',
    pageLink: null,
  },
  {
    tagId: 35,
    tagType: 'domain',
    name: 'green skills',
    tagLine: null,
    country: null,
    popularity: 46,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/134/200/300',
    pageLink: null,
  },
  {
    tagId: 36,
    tagType: 'domain',
    name: 'health',
    tagLine: null,
    country: null,
    popularity: 35,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/135/200/300',
    pageLink: null,
  },
  {
    tagId: 37,
    tagType: 'domain',
    name: 'human centered design',
    tagLine: null,
    country: null,
    popularity: 94,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/136/200/300',
    pageLink: null,
  },
  {
    tagId: 38,
    tagType: 'domain',
    name: 'human connection',
    tagLine: null,
    country: null,
    popularity: 60,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/137/200/300',
    pageLink: null,
  },
  {
    tagId: 39,
    tagType: 'domain',
    name: 'hydrogen',
    tagLine: null,
    country: null,
    popularity: 75,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/138/200/300',
    pageLink: null,
  },
  {
    tagId: 40,
    tagType: 'domain',
    name: 'innovation',
    tagLine: null,
    country: null,
    popularity: 29,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/139/200/300',
    pageLink: null,
  },
  {
    tagId: 41,
    tagType: 'domain',
    name: 'IPR regulation',
    tagLine: 'Intelectual Property Rights regulation',
    country: null,
    popularity: 93,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/140/200/300',
    pageLink: null,
  },
  {
    tagId: 42,
    tagType: 'domain',
    name: 'labour',
    tagLine: null,
    country: null,
    popularity: 28,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/141/200/300',
    pageLink: null,
  },
  {
    tagId: 43,
    tagType: 'domain',
    name: 'land use',
    tagLine: null,
    country: null,
    popularity: 3,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/142/200/300',
    pageLink: null,
  },
  {
    tagId: 44,
    tagType: 'domain',
    name: 'mobility in culture',
    tagLine: null,
    country: null,
    popularity: 27,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/143/200/300',
    pageLink: null,
  },
  {
    tagId: 45,
    tagType: 'domain',
    name: 'oceans',
    tagLine: null,
    country: null,
    popularity: 93,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/144/200/300',
    pageLink: null,
  },
  {
    tagId: 46,
    tagType: 'domain',
    name: 'organic farming',
    tagLine: null,
    country: null,
    popularity: 72,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/145/200/300',
    pageLink: null,
  },
  {
    tagId: 47,
    tagType: 'domain',
    name: 'political participation',
    tagLine: null,
    country: null,
    popularity: 90,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/146/200/300',
    pageLink: null,
  },
  {
    tagId: 48,
    tagType: 'domain',
    name: 'progressive education',
    tagLine: null,
    country: null,
    popularity: 37,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/147/200/300',
    pageLink: null,
  },
  {
    tagId: 49,
    tagType: 'domain',
    name: 'regenerative economy',
    tagLine: null,
    country: null,
    popularity: 58,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/148/200/300',
    pageLink: null,
  },
  {
    tagId: 50,
    tagType: 'domain',
    name: 'religion',
    tagLine: null,
    country: null,
    popularity: 47,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/149/200/300',
    pageLink: null,
  },
  {
    tagId: 51,
    tagType: 'domain',
    name: 'responsible research and innovation',
    tagLine: null,
    country: null,
    popularity: 30,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/150/200/300',
    pageLink: null,
  },
  {
    tagId: 52,
    tagType: 'domain',
    name: 'science',
    tagLine: null,
    country: null,
    popularity: 52,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/151/200/300',
    pageLink: null,
  },
  {
    tagId: 53,
    tagType: 'domain',
    name: 'science for policy',
    tagLine: null,
    country: null,
    popularity: 37,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/152/200/300',
    pageLink: null,
  },
  {
    tagId: 54,
    tagType: 'domain',
    name: 'social confrontations',
    tagLine: null,
    country: null,
    popularity: 58,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/153/200/300',
    pageLink: null,
  },
  {
    tagId: 55,
    tagType: 'domain',
    name: 'social innovation',
    tagLine: null,
    country: null,
    popularity: 69,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/154/200/300',
    pageLink: null,
  },
  {
    tagId: 56,
    tagType: 'domain',
    name: 'social responsibility',
    tagLine: null,
    country: null,
    popularity: 90,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/155/200/300',
    pageLink: null,
  },
  {
    tagId: 57,
    tagType: 'domain',
    name: 'sustainability',
    tagLine: null,
    country: null,
    popularity: 16,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/156/200/300',
    pageLink: null,
  },
  {
    tagId: 58,
    tagType: 'domain',
    name: 'technological change',
    tagLine: null,
    country: null,
    popularity: 76,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/157/200/300',
    pageLink: null,
  },
  {
    tagId: 59,
    tagType: 'domain',
    name: 'tourism',
    tagLine: null,
    country: null,
    popularity: 27,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/158/200/300',
    pageLink: null,
  },
  {
    tagId: 60,
    tagType: 'domain',
    name: 'transhumanism',
    tagLine: null,
    country: null,
    popularity: 10,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/159/200/300',
    pageLink: null,
  },
  {
    tagId: 61,
    tagType: 'domain',
    name: 'travel',
    tagLine: null,
    country: null,
    popularity: 83,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/160/200/300',
    pageLink: null,
  },
  {
    tagId: 62,
    tagType: 'domain',
    name: 'value chains',
    tagLine: null,
    country: null,
    popularity: 22,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/161/200/300',
    pageLink: null,
  },
  {
    tagId: 63,
    tagType: 'domain',
    name: 'youth',
    tagLine: null,
    country: null,
    popularity: 58,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/162/200/300',
    pageLink: null,
  },
  {
    tagId: 1,
    tagType: 'method',
    name: 'Delphi',
    tagLine: null,
    country: null,
    popularity: 36,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/100/200/300',
    pageLink: null,
  },
  {
    tagId: 2,
    tagType: 'method',
    name: 'deep dive',
    tagLine: null,
    country: null,
    popularity: 48,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/101/200/300',
    pageLink: null,
  },
  {
    tagId: 3,
    tagType: 'method',
    name: 'driver-mapping',
    tagLine: null,
    country: null,
    popularity: 99,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/102/200/300',
    pageLink: null,
  },
  {
    tagId: 4,
    tagType: 'method',
    name: 'expert panels',
    tagLine: null,
    country: null,
    popularity: 78,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/103/200/300',
    pageLink: null,
  },
  {
    tagId: 5,
    tagType: 'method',
    name: 'expert workshops',
    tagLine: null,
    country: null,
    popularity: 92,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/104/200/300',
    pageLink: null,
  },
  {
    tagId: 6,
    tagType: 'method',
    name: 'extrapolation',
    tagLine: null,
    country: null,
    popularity: 67,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/105/200/300',
    pageLink: null,
  },
  {
    tagId: 7,
    tagType: 'method',
    name: 'forecasting tournaments',
    tagLine: null,
    country: null,
    popularity: 96,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/106/200/300',
    pageLink: null,
  },
  {
    tagId: 8,
    tagType: 'method',
    name: 'future scenarios',
    tagLine: null,
    country: null,
    popularity: 55,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/107/200/300',
    pageLink: null,
  },
  {
    tagId: 9,
    tagType: 'method',
    name: 'futures stories',
    tagLine: null,
    country: null,
    popularity: 19,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/108/200/300',
    pageLink: null,
  },
  {
    tagId: 10,
    tagType: 'method',
    name: 'horizon scanning',
    tagLine: null,
    country: null,
    popularity: 66,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/109/200/300',
    pageLink: null,
  },
  {
    tagId: 11,
    tagType: 'method',
    name: 'horizons mapping',
    tagLine: null,
    country: null,
    popularity: 74,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/110/200/300',
    pageLink: null,
  },
  {
    tagId: 12,
    tagType: 'method',
    name: 'interviews',
    tagLine: null,
    country: null,
    popularity: 69,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/111/200/300',
    pageLink: null,
  },
  {
    tagId: 13,
    tagType: 'method',
    name: 'judgemental forecasting',
    tagLine: null,
    country: null,
    popularity: 88,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/112/200/300',
    pageLink: null,
  },
  {
    tagId: 14,
    tagType: 'method',
    name: 'lived experience storytelling',
    tagLine: null,
    country: null,
    popularity: 57,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/113/200/300',
    pageLink: null,
  },
  {
    tagId: 15,
    tagType: 'method',
    name: 'media discourse analysis',
    tagLine: null,
    country: null,
    popularity: 30,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/114/200/300',
    pageLink: null,
  },
  {
    tagId: 16,
    tagType: 'method',
    name: 'modelling',
    tagLine: null,
    country: null,
    popularity: 57,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/115/200/300',
    pageLink: null,
  },
  {
    tagId: 17,
    tagType: 'method',
    name: 'mutual learning excercise',
    tagLine: null,
    country: null,
    popularity: 2,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/116/200/300',
    pageLink: null,
  },
  {
    tagId: 18,
    tagType: 'method',
    name: 'participatory workshop-based foresight approach',
    tagLine: null,
    country: null,
    popularity: 45,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/117/200/300',
    pageLink: null,
  },
  {
    tagId: 19,
    tagType: 'method',
    name: 'policy stress-testing',
    tagLine: null,
    country: null,
    popularity: 56,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/118/200/300',
    pageLink: null,
  },
  {
    tagId: 20,
    tagType: 'method',
    name: 'scenario exercises',
    tagLine: null,
    country: null,
    popularity: 28,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/119/200/300',
    pageLink: null,
  },
  {
    tagId: 21,
    tagType: 'method',
    name: 'scenarios',
    tagLine: null,
    country: null,
    popularity: 21,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/120/200/300',
    pageLink: null,
  },
  {
    tagId: 22,
    tagType: 'method',
    name: 'social media analysis',
    tagLine: null,
    country: null,
    popularity: 29,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/121/200/300',
    pageLink: null,
  },
  {
    tagId: 23,
    tagType: 'method',
    name: 'visioning exercises',
    tagLine: null,
    country: null,
    popularity: 12,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/122/200/300',
    pageLink: null,
  },
  {
    tagId: 1,
    tagType: 'role',
    name: 'coordinator',
    tagLine: null,
    country: null,
    popularity: 59,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/100/200/300',
    pageLink: null,
  },
  {
    tagId: 2,
    tagType: 'role',
    name: 'partner',
    tagLine: null,
    country: null,
    popularity: 85,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/101/200/300',
    pageLink: null,
  },
  {
    tagId: 3,
    tagType: 'role',
    name: 'affiliate partner',
    tagLine: null,
    country: null,
    popularity: 72,
    trend: 'Stable',
    picture: 'https://picsum.photos/id/102/200/300',
    pageLink: null,
  },
  {
    tagId: 4,
    tagType: 'role',
    name: 'third-party',
    tagLine: null,
    country: null,
    popularity: 52,
    trend: 'Rising',
    picture: 'https://picsum.photos/id/103/200/300',
    pageLink: null,
  },
  {
    tagId: 5,
    tagType: 'role',
    name: 'lead of pilot project',
    tagLine: null,
    country: null,
    popularity: 15,
    trend: 'Falling',
    picture: 'https://picsum.photos/id/104/200/300',
    pageLink: null,
  },
];
