export const mockedPages = [
  {
    pageId: 1,
    title:
      'ANTICIPINNOV: Anticipation and monitoring of emerging technologies and disruptive innovation',
    subtitle: null,
    description: null,
    external_links: 'Horizon Scanning',
    involved_organisations:
      'European Commission Joint Research Centre (JRC);\nEuropean Innovation Council (EIC) ',
    logo: null,
    pageType: 'project result',
    pictures: 'https://picsum.photos/id/200/300/200',
    files: null,
  },
  {
    pageId: 63,
    title: 'Eye of Europe - The Research and Innovation foresight community',
    subtitle: 'The Research and Innovation foresight community',
    description: null,
    external_links: 'Mutual Learning Exercise, Futures literacy',
    involved_organisations:
      "Unitatea Executiva Pentru Finantarea Invatamantului Superior A Cercetarii Dezvoltarii Si Inovarii (UEFISCDI):: coordinator\nAustrian Institute Of Technology GmbH (AIT):: partner\nFraunhofer Gesellschaft Zur Forderung Der Angewandten Forschung EV (Fraunhofer):: partner\nTurun Yliopisto (UTU):: partner\nVDI/VDE Innovation + Technik GmbH (VDI/VDE IT):: partner\nDeutsches Zentrum Fur Luft - Und Raumfahrt (DLR):: partner\nFundacao Para A Ciencia E A Tecnologia (FCT):: partner\nConsiglio Nazionale Delle Ricerche (CNR):: partner\nTechnologicke Centrum Praha ZSPO (TC Praha):: partner\nAgentia Nationala pentru Cercetare si Dezvoltare (ANCD):: partner\nUrad Vlady Slovenskej Republiky (UV SR):: partner\nAsociatia Institutul De Prospectiva (Prospectiva):: partner\nInstitut National De Recherche Pour L'agriculture, L'alimentation Et L'environnement (INRAE):: partner\nS. MANTZANAKIS KAI SIA O.E (Helenos):: partner\nInsight Foresight Institute SL (IFI):: partner\nARCTIK SRL (ARCTIK):: partner\nKozgazdasag- Es Regionalis Tudomanyi Kutatokozpont (CERS):: partner\nTechnopolis:: affiliate partner",
    logo: 'https://static.wixstatic.com/media/85700c_052535d1ee184b389d8aaa13cde8598e~mv2.png/v1/fill/w_1000,h_1000,al_c,q_90,enc_auto/85700c_052535d1ee184b389d8aaa13cde8598e~mv2.png',
    pageType: 'person',
    pictures: 'https://picsum.photos/id/201/300/200',
    files: null,
  },
  {
    pageId: 109,
    title: 'RESCHAPE - Reshaping Supply Chains for a positive social impact',
    subtitle: null,
    description: null,
    external_links: null,
    involved_organisations:
      'Consiglio Nazionale delle Ricerche:: coordinator\nUniversita degli Studi di Padova:: third-party\nInstituto de Engenhariade Sistemas e Computadores, Tecnologia e Ciencia (INSEC TEC)\nFraunhofer Gesellschaft zur Forderung der Angewandten Forschung EV\nFundacion Zaragoza Logistics Center\nLeibniz Institut fur Wirtschaftsforschung e.V. (RWI)\nUniversidad de la Iglesia de Deusto Entidad Religiosa\nTechnische Universiteit Eindhoven\nIris Technology Solutions, Sociedad Limitada\nAston University',
    logo: null,
    pageType: 'organization',
    pictures: 'https://picsum.photos/id/202/300/200',
    files: null,
  },
  {
    pageId: 41,
    title:
      'Long-Term Implications of the Digital Transition for Farmers and Rural Communities',
    subtitle: null,
    description: null,
    external_links: 'Scenarios',
    involved_organisations: null,
    logo: null,
    pageType: 'organization',
    pictures: 'https://picsum.photos/id/203/300/200',
    files: null,
  },
  {
    pageId: 5,
    title: 'ESPAS Horizon Scanning',
    subtitle: null,
    description: null,
    external_links: 'Horizon scanning',
    involved_organisations:
      'European Parliament;\nCouncil of the European Union;\nEuropean Commission;\nEuropean Union External Action Service;\nEuropean Committee of the Regions;\nEuropean Economic and Social Committee;\nEuropean Investment Bank;\nEuropean Union Institute for Security Studies;\nEuropean Court of Auditors;',
    logo: 'https://espas.eu/img/ESPAS-logo.png',
    pageType: 'post',
    pictures: 'https://picsum.photos/id/204/300/200',
    files: null,
  },
  {
    pageId: 6,
    title: 'How will we disgust our descendants?',
    subtitle: null,
    description: null,
    external_links: null,
    involved_organisations: 'The Futures Literacy Company',
    logo: 'http://4cf.pl/wp-content/uploads/2022/04/MAIN-LOGO-4CF-FL-long-60.png',
    pageType: 'post',
    pictures: 'https://picsum.photos/id/205/300/200',
    files: null,
  },
  {
    pageId: 7,
    title: 'Futures Garden',
    subtitle: null,
    description: null,
    external_links: 'Speculative design',
    involved_organisations:
      'Austrian Institute of Technology;\nFraunhofer ISI;\nFutures2all; \nFuturlab; \nInstitutul de Prospectiva (Lead of pilot project);\nModem;\nNormals;',
    logo: null,
    pageType: 'post',
    pictures: 'https://picsum.photos/id/206/300/200',
    files: null,
  },
  {
    pageId: 11,
    title: 'Futures of civic resilience in Europe',
    subtitle: null,
    description: null,
    external_links: 'Scenarios, Deep Dive',
    involved_organisations: null,
    logo: null,
    pageType: 'person',
    pictures: 'https://picsum.photos/id/207/300/200',
    files: null,
  },
  {
    pageId: 29,
    title: 'FORPOL',
    subtitle: null,
    description: null,
    external_links: 'Forecasting',
    involved_organisations:
      'Ceske Priority (a non-governmental and non-profit think-tank of researchers and public sector experts);\nMetaculus (Metaculus is an online forecasting platform and aggregation engine)',
    logo: 'https://www.ceskepriority.cz/files/responsive/980/0/forpol-rgb-v1.png',
    pageType: 'organization',
    pictures: 'https://picsum.photos/id/208/300/200',
    files: null,
  },
  {
    pageId: 15,
    title: 'Actualization of Czech republic 2030 strategy',
    subtitle: null,
    description: null,
    external_links:
      'Am putea pune Expert consultation; dar asta probabil e un tag care se aplica la f multe proiecte',
    involved_organisations: 'Ceske Priority',
    logo: null,
    pageType: 'organization',
    pictures: 'https://picsum.photos/id/209/300/200',
    files: null,
  },
  {
    pageId: 11,
    title: 'Foresight for Social Innovation',
    subtitle: null,
    description: null,
    external_links: 'Expert consultation -to add?',
    involved_organisations:
      'Ceske Priority;\nMinistry of Labour and Social Affairs from Czech Republic',
    logo: null,
    pageType: 'post',
    pictures: 'https://picsum.photos/id/210/300/200',
    files: null,
  },
  {
    pageId: 81,
    title: 'EUARENAS',
    subtitle: null,
    description: null,
    external_links:
      'Horizon scanning, Scenarios, Vision\n\n(obs: am unit to ce suna a drivers si signals in horizon scanning)',
    involved_organisations:
      'University of Eastern Finland::coordinator;\nLUISS;\nEutropian;\nGdansk (Municipality?);\nPeople’s Voice Media;\nComparative Research Network (CRN) ;\nThe Department of Socio-Economic Geography at the University of Gdansk;\nDevelopment Centre of Võru County;\nUniversity of Social Sciences and Humanities (SWPS University);\nThe Municipality of Reggio Emilia;',
    logo: 'https://static.wixstatic.com/media/c1c4f0_5e336b76e7ba43f3a5096df3b0dffad2~mv2.png/v1/fill/w_518,h_162,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/horizontal_color_white.png',
    pageType: 'person',
    pictures: 'https://picsum.photos/id/211/300/200',
    files: null,
  },
  {
    pageId: 8,
    title: 'Futures of Big Tech\n\nLIPSESTE ATTACH CU RAPORTUL',
    subtitle: null,
    description: null,
    external_links: 'Scenarios, Deep Dive',
    involved_organisations: null,
    logo: null,
    pageType: 'person',
    pictures: 'https://picsum.photos/id/212/300/200',
    files: null,
  },
  {
    pageId: 14,
    title: 'FEDORA',
    subtitle: null,
    description: null,
    external_links: null,
    involved_organisations:
      'The University of Bologna (UNIBO)::coordinator;\nKaunas University of Technology;\nThe University of Helsinki;\nUniversity of Oxford;\nTeach the Future;\nformicablu\n',
    logo: 'https://www.fedora-project.eu/wp-content/uploads/2021/03/logo-fedora.svg',
    pageType: 'post',
    pictures: 'https://picsum.photos/id/213/300/200',
    files: null,
  },
  {
    pageId: 15,
    title: 'Futures of innovation and IP regulation',
    subtitle: null,
    description: null,
    external_links: 'Scenarios, Deep Dive',
    involved_organisations: null,
    logo: null,
    pageType: 'post',
    pictures: 'https://picsum.photos/id/214/300/200',
    files: null,
  },
  {
    pageId: 16,
    title: 'Futures of Green Skills and Jobs in Europe 2050',
    subtitle: null,
    description: null,
    external_links: 'Scenarios, Deep Dive',
    involved_organisations: null,
    logo: null,
    pageType: 'post',
    pictures: 'https://picsum.photos/id/215/300/200',
    files: null,
  },
  {
    pageId: 17,
    title:
      'i-Portunus Houses – Kick-Start a Local Mobility Host Network for Artists & Cultural Professionals in AllCreative Europe Countries',
    subtitle: null,
    description: null,
    external_links: 'Scenarios',
    involved_organisations:
      'European Cultural Foundation::coordinator;\nMitOst e.V.;\nKultura Nova Foundation',
    logo: null,
    pageType: 'project result',
    pictures: 'https://picsum.photos/id/216/300/200',
    files: null,
  },
  {
    pageId: 45,
    title:
      'Smart Futures Tunisia – Exploring the digital skills of tomorrow (a foresight journey into the year 2035)',
    subtitle: null,
    description: null,
    external_links: 'Scenarios',
    involved_organisations:
      'German Federal Ministry for Economic Cooperation and Development (BMZ);\nGesellschaft für Internationale Zusammenarbeit (GIZ) GmbH',
    logo: null,
    pageType: 'organization',
    pictures: 'https://picsum.photos/id/217/300/200',
    files: null,
  },
  {
    pageId: 19,
    title:
      'The Prospects of Institutionalizing the Values of Openness and Mutual Responsiveness in Science and Democracy',
    subtitle: null,
    description: null,
    external_links: null,
    involved_organisations: null,
    logo: null,
    pageType: 'project result',
    pictures: 'https://picsum.photos/id/218/300/200',
    files: null,
  },
  {
    pageId: 20,
    title: 'OrganicTargets4EU',
    subtitle: null,
    description: null,
    external_links: 'Scenarios',
    involved_organisations:
      "INTERNATIONAL FEDERATION OF ORGANIC AGRICULTURE MOVEMENTS EUROPEAN UNION REGIONAL GROUP\nFIBL EUROPE - FORSCHUNGSINSTITUTFUR BIOLOGISCHEN LANDBAU IN EUROPA\nUNIVERSITA POLITECNICA DELLE MARCHE\nFONDATION INSTITUT DE RECHERCHE POUR LE DEVELOPPEMENT DURABLE ET LES RELATIONS INTERNATIONALES\nAARHUS UNIVERSITET\nOKOLOGIAI MEZOGAZDASAGI KUTATOINTEZET KOZHASZNU NONPROFIT KFT\nJOHANN HEINRICH VON THUENEN-INSTITUT, BUNDESFORSCHUNGSINSTITUT FUER LAENDLICHE RAEUME, WALD UND FISCHEREI\nCONSULAI, CONSULTORIA AGROINDUSTRIAL LDA\nFONDAZIONE COISPA ETS\nNATURLAND - VERBAND FUR OKOLOGISCHEN LANDBAU EV\nUNIVERSITATEA SPIRU HARET\nCENTRO INTERNAZIONALE DI ALTISTUDI AGRONOMICI MEDITERRANEI\nINNOVATIONSCENTER FOR OKOLOGISK LANDBRUG P/S\nLANDWIRTSCHAFTSKAMMER NIEDEROESTERREICH\nPRASIDENTENKONFERENZ DER LANDWIRTSCHAFTSKAMMERN OSTERREICHS (third party)\nINSTITUT TECHNIQUE DE L AGRICULTURE BIOLOGIQUE\nINSTITUT NATIONAL DE RECHERCHE POUR L'AGRICULTURE, L'ALIMENTATION ET L'ENVIRONNEMENT\nARISTOTELIO PANEPISTIMIO THESSALONIKIS\nFORSCHUNGSINSTITUT FUR BIOLOGISCHEN LANDBAU STIFTUNG (partner)",
    logo: 'https://organictargets.eu/wp-content/uploads/2023/07/organic_logo.svg',
    pageType: 'project result',
    pictures: 'https://picsum.photos/id/219/300/200',
    files: null,
  },
  {
    pageId: 65,
    title:
      'Foresight for Intergenerational Decision-Making: Empowering Youth to Shape the Future',
    subtitle: null,
    description: null,
    external_links: null,
    involved_organisations: null,
    logo: null,
    pageType: 'organization',
    pictures: 'https://picsum.photos/id/220/300/200',
    files: null,
  },
  {
    pageId: 22,
    title: 'MUSAE',
    subtitle: null,
    description: null,
    external_links: null,
    involved_organisations:
      'POLITECNICO DI MILANO::coordinator;\nAB.ACUS SRL;\nUNIVERSITAT DE BARCELONA;\nMADE SCARL;\nPAL ROBOTICS SL;\nGLUON;\nUNIVERSITY COLLEGE DUBLIN, NATIONAL UNIVERSITY OF IRELAND, DUBLIN;\nELEKTROTEHNICKI FAKULTET UNIVERZITET U BEOGRADU;\nTHE UNIVERSITY OF MANCHESTER (partner)',
    logo: 'https://musae.starts.eu/wp-content/uploads/sites/3/2022/10/cropped-cropped-cropped-cropped-cropped-logo_musae_vector-2-e1666636480909.png',
    pageType: 'post',
    pictures: 'https://picsum.photos/id/221/300/200',
    files: null,
  },
  {
    pageId: 23,
    title:
      'FORGING - Industry-Academia Forum to uncover the potential of emerging enabling technologies',
    subtitle: null,
    description: null,
    external_links: null,
    involved_organisations:
      'INL International Iberian Nanotechnology Laboratory;\nG.A.C. Group;\nSTAM;\ni2CAT;\nAPRE;\nVTT',
    logo: 'https://forging-hub.eu/wp-content/uploads/2022/12/logo-2x.png',
    pageType: 'project result',
    pictures: 'https://picsum.photos/id/222/300/200',
    files: null,
  },
  {
    pageId: 24,
    title: 'GovTech Connect',
    subtitle: null,
    description: null,
    external_links: null,
    involved_organisations: null,
    logo: null,
    pageType: 'project result',
    pictures: 'https://picsum.photos/id/223/300/200',
    files: null,
  },
  {
    pageId: 25,
    title: 'Road-STEAMer',
    subtitle: null,
    description: null,
    external_links: null,
    involved_organisations:
      'Lisbon Council for Economic Competitiveness::coordinator;\nEcsite, the European Network for Science Centres and Museums;\nEllinogermaniki Agogi;\nEngineering – Ingegneria Informatica Spa;\nESHA;\nPanteion;\nPolitecnico di Milano;\nScience View;\nUniversity of Exeter;\nUniversity of Malta;\nZSI – Centre for Social Innovation;\nAssociation TRACES;\nCopernicus Science Centre;\nJunior Academy of Sciences of Ukraine',
    logo: 'https://www.road-steamer.eu/wp-content/uploads/2023/02/horizontal1.svg',
    pageType: 'project result',
    pictures: 'https://picsum.photos/id/224/300/200',
    files: null,
  },
  {
    pageId: 35,
    title:
      'Futures of interpenetration of criminal and lawful economic activities',
    subtitle: null,
    description: null,
    external_links: 'Scenarios, Deep Dive',
    involved_organisations: null,
    logo: null,
    pageType: 'person',
    pictures: 'https://picsum.photos/id/225/300/200',
    files: null,
  },
  {
    pageId: 27,
    title: 'Future Forward',
    subtitle: null,
    description: null,
    external_links: null,
    involved_organisations:
      '\nPolicy Lab;\nJoint Research Center;\nEuropean Commission',
    logo: null,
    pageType: 'post',
    pictures: 'https://picsum.photos/id/226/300/200',
    files: null,
  },
  {
    pageId: 89,
    title: 'Futures of Science for Policy in Europe',
    subtitle: null,
    description: null,
    external_links: 'Scenarios, Deep Dive',
    involved_organisations: null,
    logo: null,
    pageType: 'organization',
    pictures: 'https://picsum.photos/id/227/300/200',
    files: null,
  },
  {
    pageId: 71,
    title: 'Futures of using nature in rural and marine contexts in Europe',
    subtitle: null,
    description: null,
    external_links: 'Scenarios, Deep Dive',
    involved_organisations: null,
    logo: null,
    pageType: 'organization',
    pictures: 'https://picsum.photos/id/228/300/200',
    files: null,
  },
  {
    pageId: 30,
    title: 'Deep Dive: Social Confrontations',
    subtitle: null,
    description: null,
    external_links: 'Scenarios, Deep Dive',
    involved_organisations: null,
    logo: null,
    pageType: 'post',
    pictures: 'https://picsum.photos/id/229/300/200',
    files: null,
  },
  {
    pageId: 9,
    title: 'Travelling into the [future]',
    subtitle: null,
    description: null,
    external_links: 'Delphi, Scenarios',
    involved_organisations: 'Tipi;\nFutures Probes',
    logo: null,
    pageType: 'organization',
    pictures: 'https://picsum.photos/id/230/300/200',
    files: null,
  },
  {
    pageId: 32,
    title: 'The Millennium Project',
    subtitle: null,
    description: null,
    external_links: null,
    involved_organisations: null,
    logo: null,
    pageType: 'post',
    pictures: 'https://picsum.photos/id/231/300/200',
    files: null,
  },
  {
    pageId: 33,
    title: 'Rapid Exploration: General AI',
    subtitle: null,
    description: null,
    external_links: null,
    involved_organisations: null,
    logo: null,
    pageType: 'post',
    pictures: 'https://picsum.photos/id/232/300/200',
    files: null,
  },
  {
    pageId: 35,
    title:
      'Rapid Exploration: Rising Social Confrontations And Their Implications For Transitions',
    subtitle: null,
    description: null,
    external_links: null,
    involved_organisations: null,
    logo: null,
    pageType: 'person',
    pictures: 'https://picsum.photos/id/233/300/200',
    files: null,
  },
  {
    pageId: 33,
    title:
      'Rapid Exploration: The Future of Health Between New Threats And New Opportunities',
    subtitle: null,
    description: null,
    external_links: 'Scenarios',
    involved_organisations: null,
    logo: null,
    pageType: 'person',
    pictures: 'https://picsum.photos/id/234/300/200',
    files: null,
  },
  {
    pageId: 5,
    title:
      'Rapid Exploration: The Interpenetration of Criminal and Lawful Economic Activity',
    subtitle: null,
    description: null,
    external_links: 'Scenarios',
    involved_organisations: null,
    logo: null,
    pageType: 'person',
    pictures: 'https://picsum.photos/id/235/300/200',
    files: null,
  },
  {
    pageId: 37,
    title: 'Deep Dive: Transhumanist Revolutions',
    subtitle: null,
    description: null,
    external_links: 'Deep Dive, Scenarios, Horizon Scanning',
    involved_organisations: null,
    logo: null,
    pageType: 'project result',
    pictures: 'https://picsum.photos/id/236/300/200',
    files: null,
  },
  {
    pageId: 38,
    title: 'Deep Dive: The Hydrogen Economy: a radical Alternative',
    subtitle: null,
    description: null,
    external_links: ' Scenarios, Deep Dive',
    involved_organisations: null,
    logo: null,
    pageType: 'post',
    pictures: 'https://picsum.photos/id/237/300/200',
    files: null,
  },
  {
    pageId: 88,
    title:
      'Deep Dive: The emergence of global commons: A new opportunity for science, business, and governance',
    subtitle: null,
    description: null,
    external_links: 'Scenarios, Deep Dive',
    involved_organisations: null,
    logo: null,
    pageType: 'organization',
    pictures: 'https://picsum.photos/id/238/300/200',
    files: null,
  },
  {
    pageId: 40,
    title:
      'Deep Dive: Geopolitical Reconfiguration: The EU in a volatile new World: the challenge of global leadership',
    subtitle: null,
    description: null,
    external_links: 'Scenarios, Deep Dive',
    involved_organisations: null,
    logo: null,
    pageType: 'project result',
    pictures: 'https://picsum.photos/id/239/300/200',
    files: null,
  },
  {
    pageId: 41,
    title: 'Deep Dive: Climate & Geo-Engineering',
    subtitle: null,
    description: null,
    external_links: 'Scenarios, Deep Dive',
    involved_organisations: null,
    logo: null,
    pageType: 'post',
    pictures: 'https://picsum.photos/id/240/300/200',
    files: null,
  },
  {
    pageId: 42,
    title: 'Mutual Learning Exercise (MLE) on R&I Foresight',
    subtitle: null,
    description: null,
    external_links: 'Mutual Learning Exercise',
    involved_organisations:
      'European Commission, Research and innovation, Policy Support Facility',
    logo: null,
    pageType: 'project result',
    pictures: 'https://picsum.photos/id/241/300/200',
    files: null,
  },
  {
    pageId: 43,
    title: 'Réseau PROSPER',
    subtitle: null,
    description: null,
    external_links: null,
    involved_organisations: 'PROSPER Network',
    logo: null,
    pageType: 'post',
    pictures: 'https://picsum.photos/id/242/300/200',
    files: null,
  },
  {
    pageId: 41,
    title: 'Business Hippie Club',
    subtitle: null,
    description: null,
    external_links: null,
    involved_organisations: 'Business Hippie Club',
    logo: null,
    pageType: 'person',
    pictures: 'https://picsum.photos/id/243/300/200',
    files: null,
  },
  {
    pageId: 45,
    title: 'Time Capsule',
    subtitle: null,
    description: null,
    external_links: null,
    involved_organisations: 'Future Based',
    logo: null,
    pageType: 'project result',
    pictures: 'https://picsum.photos/id/244/300/200',
    files: null,
  },
  {
    pageId: 1,
    title: 'One Day in 2050',
    subtitle: null,
    description: null,
    external_links: 'Futures stories, Scenarios',
    involved_organisations: null,
    logo: null,
    pageType: 'organization',
    pictures: 'https://picsum.photos/id/245/300/200',
    files: null,
  },
  {
    pageId: 47,
    title:
      '\nReference Foresight Scenarios: Scenarios on the global standing of the EU in 2040',
    subtitle: null,
    description: null,
    external_links: 'Scenarios',
    involved_organisations: 'JRC EU Policy Lab',
    logo: null,
    pageType: 'project result',
    pictures: 'https://picsum.photos/id/246/300/200',
    files: null,
  },
  {
    pageId: 108,
    title:
      '4Growth project - Understanding the Market to Forecast Future Growth',
    subtitle: null,
    description: null,
    external_links: 'Scenarios, Horizon Scanning',
    involved_organisations:
      'Wageningen University & Research, Netherlands (Coordinator);\nEVENFLOW, (Technical Managers);\nGEOPONIKO PANEPISTIMION ATHINON;\nFOODSCALE HUB GREECE;\nLE EUROPE LIMITED;\nFUTURE IMPACTS;\nSIMBIOTICA SL;\nEV ILVO: EIGEN VERMOGEN VAN HET INSTITUUT VOOR LANDBOUW- EN VISSERIJONDERZOEK; \nINSTITUTO NAVARRO DE TECNOLOGIAS E INFRAESTRUCTURAS AGROALIMENTRIAS;\nCENTRE TECHNIQUE INTERPROFESSIONNEL DES FRUITS ET LEGUMES;\nTEKNOLOGIAN TUTKIMUSKESKUS VTT OY;\nAgriFood Lithuania DIH;\nARISTOTELIO PANEPISTIMIO THESSALONIKIS;',
    logo: null,
    pageType: 'organization',
    pictures: 'https://picsum.photos/id/247/300/200',
    files: null,
  },
  {
    pageId: 8,
    title: 'Teach the Future',
    subtitle: null,
    description: null,
    external_links: null,
    involved_organisations: null,
    logo: null,
    pageType: 'organization',
    pictures: 'https://picsum.photos/id/248/300/200',
    files: null,
  },
  {
    pageId: 50,
    title: 'STI for 2050',
    subtitle: null,
    description: null,
    external_links: 'Delphi, scenario dvelopment',
    involved_organisations:
      'Austrian Institute of Technology, leader;\nInsight Foresight Institute (IFI);\nInstitutul de Prospectiva;\nFraunhofer ISI;\nISINNOVA;\nVisionary Analytics',
    logo: null,
    pageType: 'post',
    pictures: 'https://picsum.photos/id/249/300/200',
    files: null,
  },
  {
    pageId: 28,
    title: 'S+T+Arts',
    subtitle: null,
    description: null,
    external_links: null,
    involved_organisations: null,
    logo: null,
    pageType: 'person',
    pictures: 'https://picsum.photos/id/250/300/200',
    files: null,
  },
  {
    pageId: 7,
    title: 'Horizon Futures Watch Newsletter',
    subtitle: null,
    description: null,
    external_links: 'Scenarios, Mutual Learning Execrcises',
    involved_organisations: null,
    logo: null,
    pageType: 'person',
    pictures: 'https://picsum.photos/id/251/300/200',
    files: null,
  },
  {
    pageId: 73,
    title: 'Earth4All',
    subtitle: null,
    description: null,
    external_links: 'Scenarios',
    involved_organisations: null,
    logo: null,
    pageType: 'person',
    pictures: 'https://picsum.photos/id/252/300/200',
    files: null,
  },
  {
    pageId: 72,
    title: 'EU Commission meets Doughnut Economics',
    subtitle: null,
    description: null,
    external_links: null,
    involved_organisations: null,
    logo: null,
    pageType: 'person',
    pictures: 'https://picsum.photos/id/253/300/200',
    files: null,
  },
  {
    pageId: 88,
    title: 'European R&I foresight and public engagement for Horizon Europe',
    subtitle: null,
    description: null,
    external_links: 'Deep Dive',
    involved_organisations: null,
    logo: null,
    pageType: 'organization',
    pictures: 'https://picsum.photos/id/254/300/200',
    files: null,
  },
  {
    pageId: 12,
    title: '#OurFutures',
    subtitle: null,
    description: null,
    external_links: 'Vision, Futures Stories, Political participation',
    involved_organisations: null,
    logo: null,
    pageType: 'person',
    pictures: 'https://picsum.photos/id/255/300/200',
    files: null,
  },
  {
    pageId: 57,
    title: 'Trigger',
    subtitle: null,
    description: null,
    external_links: 'Scenarios',
    involved_organisations:
      "CENTRE FOR EUROPEAN POLICY STUDIES;\nFRAUNHOFER GESELLSCHAFT ZUR FORDERUNG DER ANGEWANDTEN FORSCHUNG EV;\nSOCIEDADE PORTUGUESA DE INOVACAO CONSULTADORIA EMPRESARIAL E FOMENTO DA INOVACAO SA;\nISTITUTO DI STUDI PER L'INTEGRAZIONE DEI SISTEMI (I.S.I.S) - SOCIETA'COOPERATIVA;\nECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE;\nELINKEINOELAMAN TUTKIMUSLAITOKSEN KANNATUSYHDISTYS RY;\nEUROPEAN UNIVERSITY INSTITUTE;\nFREIE UNIVERSITAET BERLIN;\nTECHNISCHE UNIVERSITAET MUENCHEN;\nPOLITECNICO DI MILANO;\nASOTSCIATSIA EVROPULI GAMOKVLEVEBI SAQARTVELOS INOVACIURI GANVITAREBISTVIS;\nEURO MEDITERRANEAN ECONOMIST ASSOCIATION;\nINSTITUTION EURASIAN INSTITUTE OF INTERNATIONAL RELATIONS",
    logo: null,
    pageType: 'post',
    pictures: 'https://picsum.photos/id/256/300/200',
    files: null,
  },
  {
    pageId: 58,
    title: 'Stories from 2050',
    subtitle: null,
    description: null,
    external_links: 'Participatory Futures Workshops',
    involved_organisations: null,
    logo: null,
    pageType: 'post',
    pictures: 'https://picsum.photos/id/257/300/200',
    files: null,
  },
  {
    pageId: 59,
    title: null,
    subtitle: null,
    description: null,
    external_links: null,
    involved_organisations: null,
    logo: null,
    pageType: 'post',
    pictures: 'https://picsum.photos/id/258/300/200',
    files: null,
  },
  {
    pageId: 60,
    title: null,
    subtitle: null,
    description: null,
    external_links: null,
    involved_organisations: null,
    logo: null,
    pageType: 'project result',
    pictures: 'https://picsum.photos/id/259/300/200',
    files: null,
  },
  {
    pageId: null,
    title: null,
    subtitle: null,
    description: null,
    external_links: null,
    involved_organisations: null,
    logo: null,
    pageType: 'project result',
    pictures: 'https://picsum.photos/id/260/300/200',
    files: null,
  },
  {
    pageId: null,
    title: null,
    subtitle: null,
    description: null,
    external_links: null,
    involved_organisations:
      'am extras informatia din surse externe platformei futures4europe',
    logo: null,
    pageType: 'project result',
    pictures: 'https://picsum.photos/id/261/300/200',
    files: null,
  },
  {
    pageId: 34,
    title: null,
    subtitle: null,
    description: null,
    external_links: null,
    involved_organisations: null,
    logo: null,
    pageType: 'person',
    pictures: 'https://picsum.photos/id/262/300/200',
    files: null,
  },
  {
    pageId: null,
    title: null,
    subtitle: null,
    description: null,
    external_links: null,
    involved_organisations: 'casuta goala, nu exista informatia',
    logo: null,
    pageType: 'project result',
    pictures: 'https://picsum.photos/id/263/300/200',
    files: null,
  },
  {
    pageId: null,
    title: null,
    subtitle: null,
    description: null,
    external_links: null,
    involved_organisations:
      'ca o particularitate a proiectelor FoD incarcate, la OUTPUTS apare data publicarii: luna si anul in interiorul rap',
    logo: null,
    pageType: 'project result',
    pictures: 'https://picsum.photos/id/264/300/200',
    files: null,
  },
];
