export const mockedAssignments = [
  {
    page_id: 54,
    tagId: 6,
    field: 'domain',
    tagName: 'extrapolation',
  },
  {
    page_id: 39,
    tagId: 30,
    field: 'activity',
    tagName: 'food',
  },
  {
    page_id: 23,
    tagId: 62,
    field: 'author',
    tagName: 'value chains',
  },
  {
    page_id: 59,
    tagId: 115,
    field: 'author',
    tagName: 'University of Exeter',
  },
  {
    page_id: 40,
    tagId: 66,
    field: 'method',
    tagName: 'Ollie Bream McIntosh',
  },
  {
    page_id: 18,
    tagId: 72,
    field: 'domain',
    tagName: 'Renata Mandzhieva',
  },
  {
    page_id: 37,
    tagId: 56,
    field: 'person',
    tagName: 'social responsibility',
  },
  {
    page_id: 2,
    tagId: 31,
    field: 'person',
    tagName: 'futures stories',
  },
  {
    page_id: 29,
    tagId: 6,
    field: 'activity',
    tagName: 'extrapolation',
  },
  {
    page_id: 31,
    tagId: 112,
    field: 'country',
    tagName: 'Universitatea Spiru Haret',
  },
  {
    page_id: 55,
    tagId: 80,
    field: 'person',
    tagName: 'Simone Weske',
  },
  {
    page_id: 26,
    tagId: 30,
    field: 'project',
    tagName: 'food',
  },
  {
    page_id: 27,
    tagId: 78,
    field: 'pageType',
    tagName: 'Sanna Ahvenharjua',
  },
  {
    page_id: 50,
    tagId: 96,
    field: 'author',
    tagName: 'Teach the Future',
  },
  {
    page_id: 10,
    tagId: 63,
    field: 'domain',
    tagName: 'youth',
  },
  {
    page_id: 43,
    tagId: 96,
    field: 'activity',
    tagName: 'Teach the Future',
  },
  {
    page_id: 51,
    tagId: 92,
    field: 'method',
    tagName: 'Science View',
  },
  {
    page_id: 50,
    tagId: 50,
    field: 'author',
    tagName: 'religion',
  },
  {
    page_id: 57,
    tagId: 81,
    field: 'project',
    tagName: 'Sirkku Juhola',
  },
  {
    page_id: 33,
    tagId: 87,
    field: 'pageType',
    tagName: 'Umut Turksen',
  },
];
