export const allPagetypes = [
  'info',
  'person info',
  'organisation info',
  'project info',
  'post',
  'project result',
  'event',
  'foresight method',
];

export const fieldExcludePageTypes = {
  // field: [list of excluded pagetypes]
  author: ['info', 'person info', 'organisation info', 'project info', 'event'],
  people: ['person info', 'project info', 'project result', 'event'],
  participant: [
    'person info',
    'organisation info',
    'project result',
    'foresight method',
  ], // add new post tags as necessary
  speaker: [
    'info',
    'person info',
    'organisation info',
    'project info',
    'project result',
    'foresight method',
  ], // add new post tags as necessary
  coordinator: [
    'person info',
    'organisation info',
    'post',
    'project result',
    'event',
    'foresight method',
  ], // add new post tags as necessary
  activity: [
    'project info',
    'post',
    'project result',
    'event',
    'foresight method',
  ], // add new post tags as necessary
};
export const fieldIncludePageTypes = {
  // field: [list of included pagetypes]
  author: ['project result', 'foresight method'], // add new post tags as necessary
  people: ['organisation info', 'foresight method'], // add new post tags as necessary
  participant: ['project info', 'event'],
  speaker: ['event'],
  coordinator: ['project info'],
  activity: ['person info', 'organisation info'],
};

export const sortTags = [
  {
    tagType: 'sort',
    name: 'by begin date',
    sortAvailableFor: 'project info',
  }, // project info doar!
  { tagType: 'sort', name: 'by end date', sortAvailableFor: 'project info' }, // project info doar!
  {
    tagType: 'sort',
    name: 'by publication date',
    sortAvailableFor: 'project result',
  }, // project result doar!
  {
    tagType: 'sort',
    name: 'by established date',
    sortAvailableFor: 'organization info',
  }, // organisation info doar!
  { tagType: 'sort', name: 'by date', sortAvailableFor: 'event' }, // event doar!
];

export const mockedTags = [
  {
    tagId: 111111,
    tagType: 'organisation type',
    name: 'business',
    popularity: 20,
    trend: '5',
  },
  {
    tagId: 111112,
    tagType: 'organisation type',
    name: 'network',
    popularity: 31,
  },
  {
    tagId: 111113,
    tagType: 'organisation type',
    name: 'foresight services provider',
    popularity: 21,
  },
  {
    tagId: 111114,
    tagType: 'organisation type',
    name: 'regional public administration',
    popularity: 30,
  },
  {
    tagType: 'organisation type',
    name: 'private research organisation',
    popularity: 23,
  },
  { tagType: 'organisation type', name: 'consortium', popularity: 27 },
  {
    tagType: 'organisation type',
    name: 'foresight training provider',
    popularity: 18,
  },
  { tagType: 'organisation type', name: 'university', popularity: 26 },
  { tagType: 'organisation type', name: 'press', popularity: 19 },
  {
    tagType: 'organisation type',
    name: 'public research organisation',
    popularity: 28,
  },
  { tagType: 'organisation type', name: 'NGO', popularity: 24 },
  { tagType: 'organisation type', name: 'EU organisation', popularity: 29 },
  {
    tagType: 'organisation type',
    name: 'national public administration',
    popularity: 25,
  },
  {
    tagType: 'organisation type',
    name: 'international organisation',
    popularity: 22,
  },

  {
    tagType: 'person type',
    name: 'foresight expert',
    popularity: 12,
    trend: '3',
  },
  { tagType: 'person type', name: 'foresight trainer', popularity: 25 },
  { tagType: 'person type', name: 'domain expert', popularity: 39 },
  { tagType: 'person type', name: 'futurist', popularity: 14 },
  { tagType: 'person type', name: 'speculative design expert', popularity: 5 },
  { tagType: 'person type', name: 'journalist', popularity: 8 },
  { tagType: 'person type', name: 'R&I policy expert', popularity: 7 },
  { tagType: 'person type', name: 'impact assessment expert', popularity: 8 },
  { tagType: 'person type', name: 'foresight enthusiast', popularity: 49 },
  { tagType: 'person type', name: 'future sensitive artist', popularity: 10 },
  { tagType: 'person type', name: 'SF writer', popularity: 5 },
  { tagType: 'person type', name: 'foresight student', popularity: 3 },

  { tagType: 'project type', name: 'EU funded', popularity: 27 },

  { tagType: 'domain', name: 'agriculture', popularity: 29, trend: '3' },
  { tagType: 'domain', name: 'art', popularity: 66 },
  { tagType: 'domain', name: 'AI', popularity: 34 },
  { tagType: 'domain', name: 'awarness of the present', popularity: 54 },
  { tagType: 'domain', name: 'big tech', popularity: 51 },
  { tagType: 'domain', name: 'biodiversity', popularity: 25 },
  { tagType: 'domain', name: 'circular economy', popularity: 24 },
  { tagType: 'domain', name: 'citizen engagement', popularity: 52 },
  { tagType: 'domain', name: 'civic resilience', popularity: 63 },
  { tagType: 'domain', name: 'climate', popularity: 17 },
  { tagType: 'domain', name: 'climate change', popularity: 47 },
  { tagType: 'domain', name: 'coastal areas', popularity: 12 },
  { tagType: 'domain', name: 'community', popularity: 59 },
  { tagType: 'domain', name: 'connection to nature', popularity: 35 },
  { tagType: 'domain', name: 'criminality', popularity: 70 },
  { tagType: 'domain', name: 'cybersecurity', popularity: 53 },
  { tagType: 'domain', name: 'data', popularity: 15 },
  { tagType: 'domain', name: 'democracy', popularity: 48 },
  { tagType: 'domain', name: 'digital', popularity: 39 },
  { tagType: 'domain', name: 'digitalisation', popularity: 22 },
  { tagType: 'domain', name: 'economic crime', popularity: 50 },
  { tagType: 'domain', name: 'economy', popularity: 11 },
  { tagType: 'domain', name: 'ecosystems', popularity: 64 },
  { tagType: 'domain', name: 'education', popularity: 19 },
  { tagType: 'domain', name: 'emerging technologies', popularity: 37 },
  { tagType: 'domain', name: 'energy', popularity: 18 },
  { tagType: 'domain', name: 'ethics', popularity: 56 },
  { tagType: 'domain', name: 'EU R&I policy', popularity: 67 },
  { tagType: 'domain', name: 'fairness', popularity: 68 },
  { tagType: 'domain', name: 'food', popularity: 57 },
  { tagType: 'domain', name: 'geoengineering', popularity: 49 },
  { tagType: 'domain', name: 'geopolitics', popularity: 27 },
  { tagType: 'domain', name: 'global commons', popularity: 60 },
  { tagType: 'domain', name: 'green skills', popularity: 58 },
  { tagType: 'domain', name: 'health', popularity: 14 },
  { tagType: 'domain', name: 'human centered design', popularity: 38 },
  { tagType: 'domain', name: 'human connection', popularity: 33 },
  { tagType: 'domain', name: 'hydrogen', popularity: 40 },
  { tagType: 'domain', name: 'innovation', popularity: 69 },
  { tagType: 'domain', name: 'IPR regulation', popularity: 13 },
  { tagType: 'domain', name: 'labour', popularity: 62 },
  { tagType: 'domain', name: 'land use', popularity: 16 },
  { tagType: 'domain', name: 'mobility in culture', popularity: 36 },
  { tagType: 'domain', name: 'oceans', popularity: 41 },
  { tagType: 'domain', name: 'organic farming', popularity: 20 },
  { tagType: 'domain', name: 'political participation', popularity: 46 },
  { tagType: 'domain', name: 'progressive education', popularity: 30 },
  {
    tagType: 'domain',
    name: 'regenerative economy',
    popularity: 21,
    tagId: 1111,
  },
  { tagType: 'domain', name: 'religion', popularity: 71 },
  {
    tagType: 'domain',
    name: 'responsible research and innovation',
    popularity: 65,
  },
  { tagType: 'domain', name: 'science', popularity: 55 },
  { tagType: 'domain', name: 'science for policy', popularity: 45 },
  { tagType: 'domain', name: 'social confrontations', popularity: 61 },
  { tagType: 'domain', name: 'social innovation', popularity: 31 },
  { tagType: 'domain', name: 'social responsibility', popularity: 44 },
  { tagType: 'domain', name: 'sustainability', popularity: 26 },
  { tagType: 'domain', name: 'technological change', popularity: 28 },
  { tagType: 'domain', name: 'tourism', popularity: 42 },
  { tagType: 'domain', name: 'transhumanism', popularity: 43 },
  { tagType: 'domain', name: 'travel', popularity: 10 },
  { tagType: 'domain', name: 'value chains', popularity: 23 },
  { tagType: 'domain', name: 'youth', popularity: 72 },

  {
    tagType: 'person',
    name: 'Finn Speijer',
    linked: true,
    popularity: 8,
    trend: '5',
    picture: 'https://randomuser.me/api/portraits/thumb/men/10.jpg',
    tagline: 'Lorem ipsum dolor sit amet!',
  },
  {
    tagType: 'person',
    name: 'Knut Blind',
    linked: true,
    popularity: 59,
    trend: '4',
    picture: 'https://randomuser.me/api/portraits/thumb/men/11.jpg',
    tagline: 'Consectetur adipiscing elit',
  },
  {
    tagType: 'person',
    name: 'Mirko Boehm',
    linked: true,
    popularity: 75,
    trend: '8',
    picture: 'https://randomuser.me/api/portraits/thumb/men/12.jpg',
    tagline: 'Donec neque dolor!',
  },
  {
    tagType: 'person',
    name: 'Marta Jalšovec',
    linked: true,
    popularity: 95,
    trend: '5',
    picture: 'https://randomuser.me/api/portraits/thumb/women/13.jpg',
    tagline: 'Eleifend a neque nec',
  },
  {
    tagType: 'person',
    name: 'Moritz Hunger',
    linked: true,
    popularity: 30,
    trend: '6',
    picture: 'https://randomuser.me/api/portraits/thumb/men/14.jpg',
    tagline: 'Condimentum mattis turpis',
  },
  {
    tagType: 'person',
    name: 'Luke Georghiou',
    linked: true,
    popularity: 58,
    picture: 'https://randomuser.me/api/portraits/thumb/men/15.jpg',
    tagline: 'Phasellus velit lacus!',
  },
  {
    tagType: 'person',
    name: 'Erica Bol',
    linked: true,
    popularity: 77,
    picture: 'https://randomuser.me/api/portraits/thumb/women/16.jpg',
    tagline: 'Sodales vel dapibus vel',
  },
  {
    tagType: 'person',
    name: 'Dominik Hajduk',
    linked: true,
    popularity: 31,
    picture: 'https://randomuser.me/api/portraits/thumb/men/17.jpg',
    tagline: 'Eleifend sit amet est!',
  },
  {
    tagType: 'person',
    name: 'Carsten Claus',
    linked: true,
    popularity: 47,
    picture: 'https://randomuser.me/api/portraits/thumb/men/18.jpg',
    tagline: 'Etiam varius dui ut tellus ultrices lobortis',
  },
  {
    tagType: 'person',
    name: 'Sanna Ahvenharjua',
    linked: true,
    popularity: 64,
    picture: 'https://randomuser.me/api/portraits/thumb/women/19.jpg',
    tagline: 'Nulla malesuada fringilla odio',
  },
  {
    tagType: 'person',
    name: 'Fanny Lalot',
    linked: true,
    popularity: 79,
    picture: 'https://randomuser.me/api/portraits/thumb/women/20.jpg',
    tagline: 'Quis tempus ante vulputate sed!',
  },
  {
    tagType: 'person',
    name: 'Umut Turksen',
    linked: true,
    popularity: 3,
    picture: 'https://randomuser.me/api/portraits/thumb/men/21.jpg',
    tagline: 'Velit sed vulputate ornare',
  },
  {
    tagType: 'person',
    name: 'Rosanna Fornasiero',
    linked: true,
    popularity: 86,
    picture: 'https://randomuser.me/api/portraits/thumb/women/22.jpg',
    tagline: 'Magna leo placerat diam!',
  },
  {
    tagType: 'person',
    name: 'Simon Schmitz',
    linked: true,
    popularity: 72,
    picture: 'https://randomuser.me/api/portraits/thumb/men/23.jpg',
    tagline: 'In vehicula nibh tortor vel mi',
  },
  {
    tagType: 'person',
    name: 'Duncan McLaren',
    linked: true,
    popularity: 37,
    picture: 'https://randomuser.me/api/portraits/thumb/men/24.jpg',
    tagline: 'Sed quis ligula arcu',
  },
  {
    tagType: 'person',
    name: 'Heila Lotz-Sisitka',
    linked: true,
    popularity: 90,
    picture: 'https://randomuser.me/api/portraits/thumb/women/25.jpg',
    tagline: 'Vestibulum luctus luctus libero',
  },
  {
    tagType: 'person',
    name: 'Marina Dias',
    linked: true,
    popularity: 52,
    picture: 'https://randomuser.me/api/portraits/thumb/women/26.jpg',
    tagline: 'At ornare mi porta non!',
  },
  {
    tagType: 'person',
    name: 'Cristiano Cagnin',
    linked: true,
    popularity: 73,
    picture: 'https://randomuser.me/api/portraits/thumb/men/27.jpg',
    tagline: 'Vivamus sit',
  },
  {
    tagType: 'person',
    name: 'Sandro Mendonça',
    linked: true,
    popularity: 55,
    picture: 'https://randomuser.me/api/portraits/thumb/men/28.jpg',
  },
  {
    tagType: 'person',
    name: 'Norbert Kołos',
    linked: true,
    popularity: 5,
    picture: 'https://randomuser.me/api/portraits/thumb/men/29.jpg',
  },
  {
    tagType: 'person',
    name: 'Alexandre Reznikow',
    linked: true,
    popularity: 84,
    picture: 'https://randomuser.me/api/portraits/thumb/men/30.jpg',
  },
  {
    tagType: 'person',
    name: 'Simone Weske',
    linked: true,
    popularity: 49,
    picture: 'https://randomuser.me/api/portraits/thumb/women/31.jpg',
  },
  {
    tagType: 'person',
    name: 'Totti Könnölä',
    linked: true,
    popularity: 35,
    picture: 'https://randomuser.me/api/portraits/thumb/women/32.jpg',
  },
  {
    tagType: 'person',
    name: 'Enric Bas',
    linked: true,
    popularity: 78,
    picture: 'https://randomuser.me/api/portraits/thumb/men/33.jpg',
  },
  {
    tagType: 'person',
    name: 'Albert Norström',
    linked: true,
    popularity: 41,
    picture: 'https://randomuser.me/api/portraits/thumb/men/34.jpg',
  },
  {
    tagType: 'person',
    name: 'Maciej Jagaciak',
    linked: true,
    popularity: 54,
    picture: 'https://randomuser.me/api/portraits/thumb/men/35.jpg',
  },
  {
    tagType: 'person',
    name: 'Peter Lund',
    linked: true,
    popularity: 6,
    picture: 'https://randomuser.me/api/portraits/thumb/men/36.jpg',
  },
  {
    tagType: 'person',
    name: 'Rainer Quitzow',
    linked: true,
    popularity: 18,
    picture: 'https://randomuser.me/api/portraits/thumb/men/37.jpg',
  },
  {
    tagType: 'person',
    name: 'Matthias Weber',
    linked: true,
    popularity: 63,
    picture: 'https://randomuser.me/api/portraits/thumb/men/38.jpg',
  },
  {
    tagType: 'person',
    name: 'Corina Murafa',
    linked: true,
    popularity: 69,
    picture: 'https://randomuser.me/api/portraits/thumb/women/39.jpg',
  },
  {
    tagType: 'person',
    name: 'Lukas Jung',
    linked: true,
    popularity: 43,
    picture: 'https://randomuser.me/api/portraits/thumb/men/40.jpg',
  },
  {
    tagType: 'person',
    name: 'Marco Letizi',
    linked: true,
    popularity: 74,
    picture: 'https://randomuser.me/api/portraits/thumb/men/41.jpg',
  },
  {
    tagType: 'person',
    name: 'Elena Artiles Leyes',
    linked: true,
    popularity: 33,
    picture: 'https://randomuser.me/api/portraits/thumb/women/42.jpg',
  },
  {
    tagType: 'person',
    name: 'Kathrine Jensen',
    linked: true,
    popularity: 36,
    picture: 'https://randomuser.me/api/portraits/thumb/women/43.jpg',
  },
  {
    tagType: 'person',
    name: 'Wan J.',
    linked: true,
    popularity: 2,
    picture: 'https://randomuser.me/api/portraits/thumb/men/44.jpg',
  },
  {
    tagType: 'person',
    name: 'Peter Dickinson',
    linked: true,
    popularity: 15,
    picture: 'https://randomuser.me/api/portraits/thumb/men/45.jpg',
  },
  {
    tagType: 'person',
    name: 'Radu Gheorghiu',
    linked: true,
    popularity: 44,
    picture: 'https://randomuser.me/api/portraits/thumb/men/46.jpg',
  },
  {
    tagType: 'person',
    name: 'Alexandrova-Stefanova N.',
    linked: true,
    popularity: 28,
    picture: 'https://randomuser.me/api/portraits/thumb/men/47.jpg',
  },
  {
    tagType: 'person',
    name: 'Hywel Jones',
    linked: true,
    popularity: 42,
    picture: 'https://randomuser.me/api/portraits/thumb/men/48.jpg',
  },
  {
    tagType: 'person',
    name: 'Florian Roth',
    linked: true,
    popularity: 51,
    picture: 'https://randomuser.me/api/portraits/thumb/men/49.jpg',
  },
  {
    tagType: 'person',
    name: 'Daouia Chalali',
    linked: true,
    popularity: 12,
    picture: 'https://randomuser.me/api/portraits/thumb/women/50.jpg',
  },
  {
    tagType: 'person',
    name: 'Rene von Schomberg',
    linked: true,
    popularity: 80,
    picture: 'https://randomuser.me/api/portraits/thumb/women/51.jpg',
  },
  {
    tagType: 'person',
    name: 'Renata Mandzhieva',
    linked: true,
    popularity: 4,
    picture: 'https://randomuser.me/api/portraits/thumb/women/52.jpg',
  },
  {
    tagType: 'person',
    name: 'Michal Pazour',
    linked: true,
    popularity: 50,
    picture: 'https://randomuser.me/api/portraits/thumb/men/53.jpg',
  },
  {
    tagType: 'person',
    name: 'Mroczek Z.K.',
    linked: true,
    popularity: 10,
    picture: 'https://randomuser.me/api/portraits/thumb/men/54.jpg',
  },
  {
    tagType: 'person',
    name: 'Sabine Hafner-Zimmermann',
    linked: true,
    popularity: 70,
    picture: 'https://randomuser.me/api/portraits/thumb/women/55.jpg',
  },
  {
    tagType: 'person',
    name: 'Masafumi Nishi',
    linked: true,
    popularity: 13,
    picture: 'https://randomuser.me/api/portraits/thumb/men/56.jpg',
  },
  {
    tagType: 'person',
    name: 'Jennifer Gidley',
    linked: true,
    popularity: 67,
    picture: 'https://randomuser.me/api/portraits/thumb/women/57.jpg',
  },
  {
    tagType: 'person',
    name: 'Lourdes Rodriguez',
    linked: true,
    popularity: 60,
    picture: 'https://randomuser.me/api/portraits/thumb/men/58.jpg',
  },
  {
    tagType: 'person',
    name: 'Bianca Dragomir',
    linked: true,
    popularity: 88,
    picture: 'https://randomuser.me/api/portraits/thumb/women/59.jpg',
  },
  {
    tagType: 'person',
    name: 'Bruna De Marchi',
    linked: true,
    popularity: 83,
    picture: 'https://randomuser.me/api/portraits/thumb/men/60.jpg',
  },
  {
    tagType: 'person',
    name: 'Sirkku Juhola',
    linked: true,
    popularity: 65,
    picture: 'https://randomuser.me/api/portraits/thumb/men/61.jpg',
  },
  { tagType: 'person', name: 'Brigita Jurisic', popularity: 62 },
  { tagType: 'person', name: 'Holger Nitsch', popularity: 66 },
  { tagType: 'person', name: 'Susanne Giesecke', popularity: 76 },
  { tagType: 'person', name: 'Luk Van Langenhove', popularity: 45 },
  { tagType: 'person', name: 'Kerstin Cuhls', popularity: 1 },
  { tagType: 'person', name: 'Audouin S.', popularity: 17 },
  { tagType: 'person', name: 'Maciej Krzysztofowicz', popularity: 48 },
  { tagType: 'person', name: 'Laura Galante', popularity: 56 },
  { tagType: 'person', name: 'Ulli Lorenz', popularity: 21 },
  { tagType: 'person', name: 'Marjolein Caniels', popularity: 14 },
  { tagType: 'person', name: 'Tatiana Efremenko', popularity: 40 },
  { tagType: 'person', name: 'Catalina Martinez', popularity: 39 },
  { tagType: 'person', name: 'Katrina Günther', popularity: 20 },
  { tagType: 'person', name: 'Mikkel Knudsen', popularity: 11 },
  { tagType: 'person', name: 'Edina Löhr', popularity: 68 },
  { tagType: 'person', name: 'Dana Wasserbacher', popularity: 61 },
  { tagType: 'person', name: 'Albert Bravo-Biosca', popularity: 53 },
  { tagType: 'person', name: 'Leena Sarvaranta', popularity: 16 },
  { tagType: 'person', name: 'Aureli Soria-Frisch', popularity: 57 },
  { tagType: 'person', name: 'Kezia Barker', popularity: 46 },
  { tagType: 'person', name: 'Attila Havas', popularity: 19 },
  { tagType: 'person', name: 'Hayley Trowbridge', popularity: 7 },
  { tagType: 'person', name: 'Benjamin Sovacool', popularity: 22 },
  { tagType: 'person', name: 'Tanja Schindler', popularity: 71 },
  { tagType: 'person', name: 'Dave Shaw', popularity: 82 },
  { tagType: 'person', name: 'Maija Knutti', popularity: 38 },
  { tagType: 'person', name: 'Matti Minkkinena', popularity: 27 },
  { tagType: 'person', name: 'Kolos N.', popularity: 24 },
  { tagType: 'person', name: 'Mike Parr', popularity: 81 },
  { tagType: 'person', name: 'Ollie Bream McIntosh', popularity: 87 },
  { tagType: 'person', name: 'Wenzel Mehnert', popularity: 26 },
  { tagType: 'person', name: 'Nosarzewski K.', popularity: 23 },
  { tagType: 'person', name: 'Ron Oren', popularity: 32 },
  { tagType: 'person', name: 'Valentina Malcotti', popularity: 34 },
  { tagType: 'person', name: 'Giovanna Guiffrè', popularity: 25 },
  { tagType: 'person', name: 'Francesco Mureddu', popularity: 9 },
  { tagType: 'person', name: 'Djamen P.', popularity: 89 },
  { tagType: 'person', name: 'Philine Warnke', popularity: 29 },

  { tagType: 'foresight method', name: 'Delphi', popularity: 39, trend: '9' },
  {
    tagType: 'foresight method',
    name: 'deep dive',
    popularity: 25,
    trend: '3',
  },
  { tagType: 'foresight method', name: 'driver-mapping', popularity: 44 },
  { tagType: 'foresight method', name: 'expert panels', popularity: 28 },
  { tagType: 'foresight method', name: 'expert workshops', popularity: 33 },
  { tagType: 'foresight method', name: 'extrapolation', popularity: 38 },
  {
    tagType: 'foresight method',
    name: 'forecasting tournaments',
    popularity: 31,
  },
  { tagType: 'foresight method', name: 'future scenarios', popularity: 29 },
  { tagType: 'foresight method', name: 'futures stories', popularity: 43 },
  { tagType: 'foresight method', name: 'horizon scanning', popularity: 47 },
  { tagType: 'foresight method', name: 'horizons mapping', popularity: 35 },
  { tagType: 'foresight method', name: 'interviews', popularity: 34 },
  {
    tagType: 'foresight method',
    name: 'judgemental forecasting',
    popularity: 27,
  },
  {
    tagType: 'foresight method',
    name: 'lived experience storytelling',
    popularity: 41,
  },
  {
    tagType: 'foresight method',
    name: 'media discourse analysis',
    popularity: 32,
  },
  { tagType: 'foresight method', name: 'modelling', popularity: 46 },
  {
    tagType: 'foresight method',
    name: 'mutual learning excercise',
    popularity: 40,
  },
  {
    tagType: 'foresight method',
    name: 'participatory workshop-based foresight approach',
    popularity: 37,
  },
  {
    tagType: 'foresight method',
    name: 'policy stress-testing',
    popularity: 26,
    tagId: 2222,
  },
  { tagType: 'foresight method', name: 'scenario exercises', popularity: 45 },
  { tagType: 'foresight method', name: 'scenarios', popularity: 36 },
  {
    tagType: 'foresight method',
    name: 'social media analysis',
    popularity: 30,
  },
  { tagType: 'foresight method', name: 'visioning exercises', popularity: 42 },

  {
    tagType: 'project',
    linked: true,
    name: 'Futures of using nature in rural and marine contexts in Europe',
    popularity: 19,
    trend: '5',
  },
  {
    tagType: 'project',
    linked: true,
    name: 'Geopolitical Reconfiguration',
    popularity: 22,
    trend: '7',
    tagline:
      'The EU in a volatile new World: the challenge of global leadership',
  },
  {
    tagType: 'project',
    linked: true,
    name: 'i-Portunus Houses',
    popularity: 35,
    trend: '4',
    tagline:
      'Kick-Start a Local Mobility Host Network for Artists & Cultural Professionals in AllCreative Europe Countries',
  },
  {
    tagType: 'project',
    linked: true,
    name: 'Réseau PROSPER',
    popularity: 33,
    trend: '3',
  },
  {
    tagType: 'project',
    linked: true,
    name: 'Foresight for Social Innovation',
    popularity: 18,
  },
  {
    tagType: 'project',
    linked: true,
    name: 'The Millennium Project',
    popularity: 41,
  },
  {
    tagType: 'project',
    linked: true,
    name: 'RESCHAPE',
    popularity: 39,
    tagline: 'Reshaping Supply Chains for a positive social impact',
  },
  { tagType: 'project', linked: true, name: 'Future Forward', popularity: 37 },
  {
    tagType: 'project',
    linked: true,
    name: 'Futures of Big Tech',
    popularity: 12,
  },
  {
    tagType: 'project',
    linked: true,
    name: 'How will we disgust our descendants?',
    popularity: 52,
  },
  { tagType: 'project', linked: true, name: 'GovTech Connect', popularity: 20 },
  {
    tagType: 'project',
    linked: true,
    name: 'The Future of Health Between New Threats And New Opportunities',
    popularity: 11,
  },
  { tagType: 'project', linked: true, name: 'Futures Garden', popularity: 44 },
  {
    tagType: 'project',
    linked: true,
    name: 'Travelling into the [future]',
    popularity: 28,
  },
  { tagType: 'project', linked: true, name: 'Time Capsule', popularity: 26 },
  {
    tagType: 'project',
    linked: true,
    name: 'Mutual Learning Exercise (MLE) on R&I Foresight',
    popularity: 36,
  },
  {
    tagType: 'project',
    name: 'ANTICIPINNOV',
    popularity: 17,
    tagline:
      'Anticipation and monitoring of emerging technologies and disruptive innovation',
  },
  { tagType: 'project', name: 'One Day in 2050', popularity: 30 },
  {
    tagType: 'project',
    name: 'Foresight for Intergenerational Decision-Making',
    popularity: 16,
    tagline: 'Empowering Youth to Shape the Future',
  },
  {
    tagType: 'project',
    name: 'Futures of civic resilience in Europe',
    popularity: 40,
  },
  {
    tagType: 'project',
    name: 'Rising Social Confrontations And Their Implications For Transitions',
    popularity: 7,
  },
  { tagType: 'project', name: 'EUARENAS', popularity: 23 },
  {
    tagType: 'project',
    name: 'Futures of interpenetration of criminal and lawful economic activities',
    popularity: 15,
  },
  { tagType: 'project', name: 'ESPAS Horizon Scanning', popularity: 25 },
  { tagType: 'project', name: 'General AI', popularity: 3 },
  {
    tagType: 'project',
    name: 'Eye of Europe',
    popularity: 45,
    tagline: 'The Research and Innovation foresight community',
  },
  { tagType: 'project', name: 'OrganicTargets4EU', popularity: 5 },
  { tagType: 'project', name: 'FEDORA', popularity: 42 },
  {
    tagType: 'project',
    name: 'The Hydrogen Economy: a radical Alternative',
    popularity: 2,
  },
  {
    tagType: 'project',
    name: 'The Interpenetration of Criminal and Lawful Economic Activity',
    popularity: 34,
  },
  {
    tagType: 'project',
    name: 'The emergence of global commons',
    popularity: 29,
    tagline: 'A new opportunity for science, business, and governance',
  },
  {
    tagType: 'project',
    name: 'Futures of innovation and IP regulation',
    popularity: 38,
  },
  { tagType: 'project', name: 'Social Confrontations', popularity: 8 },
  {
    tagType: 'project',
    name: 'Futures of Green Skills and Jobs in Europe 2050',
    popularity: 21,
  },
  {
    tagType: 'project',
    name: 'Long-Term Implications of the Digital Transition for Farmers and Rural Communities',
    popularity: 43,
  },
  {
    tagType: 'project',
    name: 'Smart Futures Tunisia',
    popularity: 4,
    tagline:
      'Exploring the digital skills of tomorrow (a foresight journey into the year 2035)',
  },
  { tagType: 'project', name: 'Road-STEAMer', popularity: 32 },
  { tagType: 'project', name: 'Transhumanist Revolutions', popularity: 31 },
  { tagType: 'project', name: 'Business Hippie Club', popularity: 13 },
  { tagType: 'project', name: 'Climate & Geo-Engineering', popularity: 27 },
  { tagType: 'project', name: 'FORPOL', popularity: 10 },
  {
    tagType: 'project',
    name: 'Actualization of Czech republic 2030 strategy',
    popularity: 14,
  },
  {
    tagType: 'project',
    name: 'Futures of Science for Policy in Europe',
    popularity: 24,
  },
  { tagType: 'project', name: 'MUSAE', popularity: 6 },
  {
    tagType: 'project',
    name: 'FORGING',
    popularity: 9,
    tagline:
      'Industry-Academia Forum to uncover the potential of emerging enabling technologies',
  },

  {
    tagType: 'organisation',
    linked: true,
    name: 'UEFISCDI',
    popularity: 55,
    trend: '5',
    tagline:
      'Unitatea Executivă pentru Finanțarea Învățământului superior, a Cercetării, Dezvoltării și Inovării',
    picture:
      'https://uefiscdi.gov.ro/src/org/uefiscdi/template/css/img/uefiscdi-logo-albastru.svg',
  },
  {
    tagType: 'organisation',
    linked: true,
    name: 'The Department of Socio-Economic Geography at the University of Gdansk',
    popularity: 29,
    trend: '9',
  },
  {
    tagType: 'organisation',
    linked: true,
    name: 'University of Oxford',
    popularity: 82,
    trend: '12',
  },
  {
    tagType: 'organisation',
    linked: true,
    name: 'Fondazione Coispa ETS',
    popularity: 75,
    trend: '3',
  },
  {
    tagType: 'organisation',
    linked: true,
    name: 'Engineering – Ingegneria Informatica Spa',
    popularity: 32,
  },
  { tagType: 'organisation', linked: true, name: 'Tipi', popularity: 65 },
  {
    tagType: 'organisation',
    linked: true,
    name: 'Business Hippie Club',
    popularity: 81,
  },
  {
    tagType: 'organisation',
    linked: true,
    name: 'RWI',
    popularity: 88,
    tagline: 'Leibniz Institut fur Wirtschaftsforschung e.V.',
  },
  {
    tagType: 'organisation',
    linked: true,
    name: 'Technische Universiteit Eindhoven',
    popularity: 104,
  },
  {
    tagType: 'organisation',
    linked: true,
    name: 'Aarhus Universitet',
    popularity: 108,
  },
  {
    tagType: 'organisation',
    linked: true,
    name: 'CNR',
    popularity: 12,
    tagline: 'Consiglio Nazionale delle Ricerche',
  },
  {
    tagType: 'organisation',
    linked: true,
    name: 'European Union External Action Service',
    popularity: 13,
  },
  { tagType: 'organisation', linked: true, name: 'STAM', popularity: 93 },
  {
    tagType: 'organisation',
    name: 'Johann Heinrich Von Thuenen-Institut',
    popularity: 71,
    tagline:
      'Bundesforschungsinstitut Fuer Laendliche Raeume, Wald und Fischerei',
  },
  { tagType: 'organisation', name: 'University of Exeter', popularity: 101 },
  {
    tagType: 'organisation',
    name: 'SWPS University',
    popularity: 7,
    tagline: 'University of Social Sciences and Humanities',
  },
  {
    tagType: 'organisation',
    name: 'Prasidentenkonferenz der Landwirtschaftskammern Osterreichs',
    popularity: 25,
  },
  { tagType: 'organisation', name: 'Aston University', popularity: 45 },
  {
    tagType: 'organisation',
    name: 'Centro Internazionale di Altistudi Agronomici Mediterranei',
    popularity: 78,
  },
  { tagType: 'organisation', name: 'Futurlab', popularity: 5 },
  { tagType: 'organisation', name: 'formicablu', popularity: 55 },
  {
    tagType: 'organisation',
    name: 'The Futures Literacy Company',
    popularity: 47,
  },
  { tagType: 'organisation', name: 'Eutropian', popularity: 85 },
  { tagType: 'organisation', name: 'European Investment Bank', popularity: 17 },
  {
    tagType: 'organisation',
    name: 'JRC',
    popularity: 40,
    tagline: 'European Commission Joint Research Centre',
  },
  {
    tagType: 'organisation',
    name: 'The University of Bologna',
    popularity: 114,
    tagline: 'UNIBO',
  },
  { tagType: 'organisation', name: 'G.A.C. Group', popularity: 2 },
  { tagType: 'organisation', name: 'Joint Research Center', popularity: 50 },
  {
    tagType: 'organisation',
    name: 'European Cultural Foundation',
    popularity: 67,
  },
  {
    tagType: 'organisation',
    name: 'Junior Academy of Sciences of Ukraine',
    popularity: 38,
  },
  {
    tagType: 'organisation',
    name: 'CRN',
    popularity: 98,
    tagline: 'Comparative Research Network',
  },
  {
    tagType: 'organisation',
    name: 'Universita degli Studi di Padova',
    popularity: 22,
  },
  {
    tagType: 'organisation',
    name: 'CERS',
    popularity: 9,
    tagline: 'Kozgazdasag - Es Regionalis Tudomanyi Kutatokozpont',
  },
  {
    tagType: 'organisation',
    name: 'Universidad de la Iglesia de Deusto Entidad Religiosa',
    popularity: 107,
  },
  { tagType: 'organisation', name: 'ARCTIK SRL', popularity: 115 },
  {
    tagType: 'organisation',
    name: 'EIC',
    popularity: 26,
    tagline: 'European Innovation Council',
  },
  {
    tagType: 'organisation',
    name: 'European Union Institute for Security Studies',
    popularity: 80,
  },
  {
    tagType: 'organisation',
    name: 'Elektrotehnicki Fakultet Univerzitet u Beogradu',
    popularity: 73,
  },
  {
    tagType: 'organisation',
    name: 'NATURLAND',
    popularity: 56,
    tagline: 'Verband fur Okologischen Landbau Ev',
  },
  {
    tagType: 'organisation',
    name: 'Landwirtschaftskammer Niederoesterreich',
    popularity: 97,
  },
  {
    tagType: 'organisation',
    name: 'Universita Politecnica delle Marche',
    popularity: 87,
  },
  { tagType: 'organisation', name: 'Normals', popularity: 96 },
  {
    tagType: 'organisation',
    name: 'University of Eastern Finland',
    popularity: 105,
  },
  {
    tagType: 'organisation',
    name: 'University College Dublin, National University of Ireland, Dublin',
    popularity: 95,
  },
  { tagType: 'organisation', name: 'People’s Voice Media', popularity: 118 },
  { tagType: 'organisation', name: 'Association TRACES', popularity: 43 },
  { tagType: 'organisation', name: 'i2CAT', popularity: 110 },
  {
    tagType: 'organisation',
    name: 'Council of the European Union',
    popularity: 117,
  },
  {
    tagType: 'organisation',
    name: 'Ceske Priority',
    popularity: 4,
    tagline:
      'non-governmental and non-profit think-tank of researchers and public sector experts',
  },
  { tagType: 'organisation', name: 'ESHA', popularity: 44 },
  { tagType: 'organisation', name: 'Futures2all', popularity: 119 },
  { tagType: 'organisation', name: 'University of Malta', popularity: 112 },
  {
    tagType: 'organisation',
    name: 'UV SR',
    popularity: 103,
    tagline: 'Urad Vlady Slovenskej Republiky',
  },
  {
    tagType: 'organisation',
    name: 'S. Mantzanakis KAI SIA O.E (Helenos)',
    popularity: 74,
  },
  {
    tagType: 'organisation',
    name: 'European Committee of the Regions',
    popularity: 57,
  },
  {
    tagType: 'organisation',
    name: 'The Municipality of Reggio Emilia',
    popularity: 28,
  },
  {
    tagType: 'organisation',
    name: 'Ecsite',
    popularity: 60,
    tagline: 'The European Network for Science Centres and Museums',
  },
  { tagType: 'organisation', name: 'Gdansk (Municipality?)', popularity: 91 },
  {
    tagType: 'organisation',
    name: 'International Federation of Organic Agriculture Movements European Union Regional Group',
    popularity: 64,
  },
  {
    tagType: 'organisation',
    name: 'TC Praha',
    popularity: 68,
    tagline: 'Technologicke Centrum Praha ZSPO',
  },
  { tagType: 'organisation', name: 'Politecnico di Milano', popularity: 34 },
  {
    tagType: 'organisation',
    name: 'ZSI',
    popularity: 37,
    tagline: 'Centre for Social Innovation',
  },
  { tagType: 'organisation', name: 'LUISS', popularity: 11 },
  {
    tagType: 'organisation',
    name: 'Turun Yliopisto',
    popularity: 39,
    tagline: 'UTU',
  },
  {
    tagType: 'organisation',
    name: 'INSEC TEC',
    popularity: 116,
    tagline:
      'Instituto de Engenhariade Sistemas e Computadores, Tecnologia e Ciencia',
  },
  {
    tagType: 'organisation',
    name: 'The University of Manchester',
    popularity: 15,
  },
  { tagType: 'organisation', name: 'AB.ACUS SRL', popularity: 51 },
  {
    tagType: 'organisation',
    name: 'German Federal Ministry for Economic Cooperation and Development',
    popularity: 20,
    tagline: 'BMZ',
  },
  {
    tagType: 'organisation',
    name: 'Fraunhofer',
    popularity: 14,
    tagline:
      'Fraunhofer Gesellschaft Zur Forderung Der Angewandten Forschung EV',
  },
  { tagType: 'organisation', name: 'Fraunhofer ISI', popularity: 106 },
  {
    tagType: 'organisation',
    name: 'Aristotelio Panepistimio Thessalonikis',
    popularity: 6,
  },
  { tagType: 'organisation', name: 'MADE SCARL', popularity: 89 },
  { tagType: 'organisation', name: 'VTT', popularity: 52 },
  { tagType: 'organisation', name: 'European Commission', popularity: 92 },
  {
    tagType: 'organisation',
    name: 'Iris Technology Solutions Sociedad Limitada',
    popularity: 58,
  },
  {
    tagType: 'organisation',
    name: 'DLR',
    popularity: 21,
    tagline: 'Deutsches Zentrum Fur Luft - Und Raumfahrt',
  },
  { tagType: 'organisation', name: 'Panteion', popularity: 70 },
  { tagType: 'organisation', name: 'European Parliament', popularity: 59 },
  {
    tagType: 'organisation',
    name: 'Development Centre of Võru County',
    popularity: 42,
  },
  {
    tagType: 'organisation',
    name: 'European Commission, Research and innovation, Policy Support Facility',
    popularity: 31,
  },
  {
    tagType: 'organisation',
    name: 'GIZ',
    popularity: 62,
    tagline: 'Gesellschaft für Internationale Zusammenarbeit GmbH',
  },
  { tagType: 'organisation', name: 'Modem', popularity: 99 },
  {
    tagType: 'organisation',
    name: 'European Court of Auditors',
    popularity: 94,
  },
  {
    tagType: 'organisation',
    name: 'Copernicus Science Centre',
    popularity: 63,
  },
  {
    tagType: 'organisation',
    name: 'VDI/VDE IT',
    popularity: 1,
    tagline: 'VDI/VDE Innovation + Technik GmbH',
  },
  { tagType: 'organisation', name: 'GLUON', popularity: 53 },
  { tagType: 'organisation', name: 'Future Based', popularity: 79 },
  {
    tagType: 'organisation',
    name: 'IFI',
    popularity: 30,
    tagline: 'Insight Foresight Institute SL',
  },
  {
    tagType: 'organisation',
    name: 'FCT',
    popularity: 19,
    tagline: 'Fundacao Para A Ciencia E A Tecnologia',
  },
  { tagType: 'organisation', name: 'APRE', popularity: 16 },
  { tagType: 'organisation', name: 'PAL Robotics SL', popularity: 23 },
  {
    tagType: 'organisation',
    name: 'Lisbon Council for Economic Competitiveness',
    popularity: 90,
  },
  {
    tagType: 'organisation',
    name: 'European Economic and Social Committee',
    popularity: 46,
  },
  { tagType: 'organisation', name: 'MitOst e.V.', popularity: 61 },
  { tagType: 'organisation', name: 'Kultura Nova Foundation', popularity: 3 },
  { tagType: 'organisation', name: 'Technopolis', popularity: 76 },
  { tagType: 'organisation', name: 'Teach the Future', popularity: 54 },
  {
    tagType: 'organisation',
    name: 'Prospectiva',
    popularity: 35,
    tagline: 'Asociația Institutul de Prospectivă',
  },
  {
    tagType: 'organisation',
    name: 'Fundacion Zaragoza Logistics Center',
    popularity: 10,
  },
  {
    tagType: 'organisation',
    name: 'Universitatea Spiru Haret',
    popularity: 100,
  },
  { tagType: 'organisation', name: 'Science View', popularity: 41 },
  {
    tagType: 'organisation',
    name: 'CONSULAI',
    popularity: 113,
    tagline: 'Consultoria Agroindustrial LDA',
  },
  {
    tagType: 'organisation',
    name: 'Fondation Institut de Recherche pour le Developpement Durable et les Relations Internationales',
    popularity: 102,
  },
  {
    tagType: 'organisation',
    name: 'Ministry of Labour and Social Affairs from Czech Republic',
    popularity: 83,
  },
  {
    tagType: 'organisation',
    name: 'AIT',
    popularity: 49,
    tagline: 'Austrian Institute Of Technology GmbH',
  },
  {
    tagType: 'organisation',
    name: 'Kaunas University of Technology',
    popularity: 111,
  },
  {
    tagType: 'organisation',
    name: 'ANCD',
    popularity: 72,
    tagline: 'Agenția Națională pentru Cercetare și Dezvoltare',
  },
  {
    tagType: 'organisation',
    name: 'Institut Technique de l Agriculture Biologique',
    popularity: 120,
  },
  { tagType: 'organisation', name: 'PROSPER Network', popularity: 77 },
  {
    tagType: 'organisation',
    name: 'INRAE',
    popularity: 84,
    tagline:
      "Institut National De Recherche Pour L'agriculture, L'alimentation Et L'environnement",
  },
  {
    tagType: 'organisation',
    name: 'FIBL Europe',
    popularity: 69,
    tagline: 'Forschungsinstitutfur Biologischen Landbau in Europa',
  },
  { tagType: 'organisation', name: 'Futures Probes', popularity: 33 },
  {
    tagType: 'organisation',
    name: 'INL',
    popularity: 86,
    tagline: 'International Iberian Nanotechnology Laboratory',
  },
  { tagType: 'organisation', name: 'Policy Lab', popularity: 109 },
  {
    tagType: 'organisation',
    name: 'Forschungsinstitut fur Biologischen Landbau Stiftung',
    popularity: 36,
  },
  {
    tagType: 'organisation',
    name: 'Okologiai Mezogazdasagi Kutatointezet Kozhasznu',
    popularity: 27,
    tagline: 'Nonprofit Kft',
  },
  {
    tagType: 'organisation',
    name: 'The University of Helsinki',
    popularity: 48,
  },
  { tagType: 'organisation', name: 'Ellinogermaniki Agogi', popularity: 66 },
  {
    tagType: 'organisation',
    name: 'Innovationscenter for Okologisk Landbrug P/S',
    popularity: 18,
  },
  {
    tagType: 'organisation',
    name: 'Metaculus',
    popularity: 8,
    tagline: 'online forecasting platform and aggregation engine',
  },
  { tagType: 'organisation', name: 'Universitat de Barcelona', popularity: 24 },

  { tagType: 'country', name: 'Cyprus', popularity: 9 },
  { tagType: 'country', name: 'Iceland', popularity: 3 },
  { tagType: 'country', name: 'Austria', popularity: 14 },
  { tagType: 'country', name: 'Armenia', popularity: 18 },
  { tagType: 'country', name: 'Spain', popularity: 33 },
  { tagType: 'country', name: 'Montenegro', popularity: 46 },
  { tagType: 'country', name: 'Ukraine', popularity: 28 },
  { tagType: 'country', name: 'Finland', popularity: 42 },
  { tagType: 'country', name: 'San Marino', popularity: 37 },
  { tagType: 'country', name: 'Norway', popularity: 1 },
  { tagType: 'country', name: 'Bosnia and Herzegovina', popularity: 17 },
  { tagType: 'country', name: 'Romania', popularity: 15 },
  { tagType: 'country', name: 'Ireland', popularity: 38 },
  { tagType: 'country', name: 'Kosovo', popularity: 34 },
  { tagType: 'country', name: 'Serbia', popularity: 43 },
  { tagType: 'country', name: 'Malta', popularity: 36 },
  { tagType: 'country', name: 'Lithuania', popularity: 11 },
  { tagType: 'country', name: 'United Kingdom', popularity: 6 },
  { tagType: 'country', name: 'Portugal', popularity: 19 },
  { tagType: 'country', name: 'Greece', popularity: 22 },
  { tagType: 'country', name: 'Estonia', popularity: 20 },
  { tagType: 'country', name: 'Slovakia', popularity: 12 },
  { tagType: 'country', name: 'Turkey', popularity: 24 },
  { tagType: 'country', name: 'Italy', popularity: 48 },
  {
    tagType: 'country',
    name: 'Former Yugoslav Republic of Macedonia',
    popularity: 4,
  },
  { tagType: 'country', name: 'Denmark', popularity: 39 },
  { tagType: 'country', name: 'Georgia', popularity: 23 },
  { tagType: 'country', name: 'Croatia', popularity: 26 },
  { tagType: 'country', name: 'Germany', popularity: 45 },
  { tagType: 'country', name: 'Luxembourg', popularity: 47 },
  { tagType: 'country', name: 'Latvia', popularity: 2 },
  { tagType: 'country', name: 'Monaco', popularity: 21 },
  { tagType: 'country', name: 'Poland', popularity: 16 },
  { tagType: 'country', name: 'Azerbaijan', popularity: 7 },
  { tagType: 'country', name: 'Sweden', popularity: 40 },
  { tagType: 'country', name: 'Liechtenstein', popularity: 41 },
  { tagType: 'country', name: 'Sweden', popularity: 30 },
  { tagType: 'country', name: 'Slovenia', popularity: 27 },
  { tagType: 'country', name: 'Netherlands', popularity: 13 },
  { tagType: 'country', name: 'Russia', popularity: 49 },
  { tagType: 'country', name: 'Hungary', popularity: 50 },
  { tagType: 'country', name: 'Switzerland', popularity: 29 },
  { tagType: 'country', name: 'Czech Republic', popularity: 25 },
  { tagType: 'country', name: 'France', popularity: 32 },
  { tagType: 'country', name: 'Bulgaria', popularity: 10 },
  { tagType: 'country', name: 'Belgium', popularity: 5 },
  { tagType: 'country', name: 'Andorra', popularity: 44 },
  { tagType: 'country', name: 'Albania', popularity: 8 },
  { tagType: 'country', name: 'Belarus', popularity: 31 },
  { tagType: 'country', name: 'Moldova', popularity: 35 },
];
